// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$381 {

    static final FunctionDescriptor glib_autoptr_cleanup_GIOChannel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GIOChannel$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GIOChannel",
        constants$381.glib_autoptr_cleanup_GIOChannel$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GIOChannel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GIOChannel$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GIOChannel",
        constants$381.glib_listautoptr_cleanup_GIOChannel$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GIOChannel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GIOChannel$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GIOChannel",
        constants$381.glib_slistautoptr_cleanup_GIOChannel$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GIOChannel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GIOChannel$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GIOChannel",
        constants$381.glib_queueautoptr_cleanup_GIOChannel$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GKeyFile$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GKeyFile$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GKeyFile",
        constants$381.glib_autoptr_clear_GKeyFile$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GKeyFile$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GKeyFile$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GKeyFile",
        constants$381.glib_autoptr_cleanup_GKeyFile$FUNC, false
    );
}


