// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1521 {

    static final FunctionDescriptor gtk_tree_row_reference_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_row_reference_copy$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_row_reference_copy",
        constants$1521.gtk_tree_row_reference_copy$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_row_reference_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_row_reference_free$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_row_reference_free",
        constants$1521.gtk_tree_row_reference_free$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_row_reference_inserted$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_row_reference_inserted$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_row_reference_inserted",
        constants$1521.gtk_tree_row_reference_inserted$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_row_reference_deleted$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_row_reference_deleted$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_row_reference_deleted",
        constants$1521.gtk_tree_row_reference_deleted$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_row_reference_reordered$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_row_reference_reordered$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_row_reference_reordered",
        constants$1521.gtk_tree_row_reference_reordered$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_iter_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_iter_copy$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_iter_copy",
        constants$1521.gtk_tree_iter_copy$FUNC, false
    );
}


