// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$985 {

    static final FunctionDescriptor hb_set_intersect$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_set_intersect$MH = RuntimeHelper.downcallHandle(
        "hb_set_intersect",
        constants$985.hb_set_intersect$FUNC, false
    );
    static final FunctionDescriptor hb_set_subtract$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_set_subtract$MH = RuntimeHelper.downcallHandle(
        "hb_set_subtract",
        constants$985.hb_set_subtract$FUNC, false
    );
    static final FunctionDescriptor hb_set_symmetric_difference$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_set_symmetric_difference$MH = RuntimeHelper.downcallHandle(
        "hb_set_symmetric_difference",
        constants$985.hb_set_symmetric_difference$FUNC, false
    );
    static final FunctionDescriptor hb_set_get_population$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_set_get_population$MH = RuntimeHelper.downcallHandle(
        "hb_set_get_population",
        constants$985.hb_set_get_population$FUNC, false
    );
    static final FunctionDescriptor hb_set_get_min$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_set_get_min$MH = RuntimeHelper.downcallHandle(
        "hb_set_get_min",
        constants$985.hb_set_get_min$FUNC, false
    );
    static final FunctionDescriptor hb_set_get_max$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_set_get_max$MH = RuntimeHelper.downcallHandle(
        "hb_set_get_max",
        constants$985.hb_set_get_max$FUNC, false
    );
}


