// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$220 {

    static final FunctionDescriptor g_variant_new_objv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_variant_new_objv$MH = RuntimeHelper.downcallHandle(
        "g_variant_new_objv",
        constants$220.g_variant_new_objv$FUNC, false
    );
    static final FunctionDescriptor g_variant_new_bytestring$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_new_bytestring$MH = RuntimeHelper.downcallHandle(
        "g_variant_new_bytestring",
        constants$220.g_variant_new_bytestring$FUNC, false
    );
    static final FunctionDescriptor g_variant_new_bytestring_array$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_variant_new_bytestring_array$MH = RuntimeHelper.downcallHandle(
        "g_variant_new_bytestring_array",
        constants$220.g_variant_new_bytestring_array$FUNC, false
    );
    static final FunctionDescriptor g_variant_new_fixed_array$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_variant_new_fixed_array$MH = RuntimeHelper.downcallHandle(
        "g_variant_new_fixed_array",
        constants$220.g_variant_new_fixed_array$FUNC, false
    );
    static final FunctionDescriptor g_variant_get_boolean$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_get_boolean$MH = RuntimeHelper.downcallHandle(
        "g_variant_get_boolean",
        constants$220.g_variant_get_boolean$FUNC, false
    );
    static final FunctionDescriptor g_variant_get_byte$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_get_byte$MH = RuntimeHelper.downcallHandle(
        "g_variant_get_byte",
        constants$220.g_variant_get_byte$FUNC, false
    );
}


