// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2307 {

    static final MemorySegment G_FILE_ATTRIBUTE_STANDARD_EDIT_NAME$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("standard::edit-name");
    static final MemorySegment G_FILE_ATTRIBUTE_STANDARD_COPY_NAME$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("standard::copy-name");
    static final MemorySegment G_FILE_ATTRIBUTE_STANDARD_DESCRIPTION$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("standard::description");
    static final MemorySegment G_FILE_ATTRIBUTE_STANDARD_ICON$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("standard::icon");
    static final MemorySegment G_FILE_ATTRIBUTE_STANDARD_SYMBOLIC_ICON$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("standard::symbolic-icon");
    static final MemorySegment G_FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("standard::content-type");
}


