// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$681 {

    static final FunctionDescriptor g_file_info_set_attribute$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_info_set_attribute$MH = RuntimeHelper.downcallHandle(
        "g_file_info_set_attribute",
        constants$681.g_file_info_set_attribute$FUNC, false
    );
    static final FunctionDescriptor g_file_info_set_attribute_string$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_info_set_attribute_string$MH = RuntimeHelper.downcallHandle(
        "g_file_info_set_attribute_string",
        constants$681.g_file_info_set_attribute_string$FUNC, false
    );
    static final FunctionDescriptor g_file_info_set_attribute_byte_string$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_info_set_attribute_byte_string$MH = RuntimeHelper.downcallHandle(
        "g_file_info_set_attribute_byte_string",
        constants$681.g_file_info_set_attribute_byte_string$FUNC, false
    );
    static final FunctionDescriptor g_file_info_set_attribute_boolean$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_file_info_set_attribute_boolean$MH = RuntimeHelper.downcallHandle(
        "g_file_info_set_attribute_boolean",
        constants$681.g_file_info_set_attribute_boolean$FUNC, false
    );
    static final FunctionDescriptor g_file_info_set_attribute_uint32$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_file_info_set_attribute_uint32$MH = RuntimeHelper.downcallHandle(
        "g_file_info_set_attribute_uint32",
        constants$681.g_file_info_set_attribute_uint32$FUNC, false
    );
    static final FunctionDescriptor g_file_info_set_attribute_int32$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_file_info_set_attribute_int32$MH = RuntimeHelper.downcallHandle(
        "g_file_info_set_attribute_int32",
        constants$681.g_file_info_set_attribute_int32$FUNC, false
    );
}


