// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1814 {

    static final FunctionDescriptor gtk_icon_view_get_row_spacing$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_view_get_row_spacing$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_get_row_spacing",
        constants$1814.gtk_icon_view_get_row_spacing$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_view_set_column_spacing$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_icon_view_set_column_spacing$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_set_column_spacing",
        constants$1814.gtk_icon_view_set_column_spacing$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_view_get_column_spacing$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_view_get_column_spacing$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_get_column_spacing",
        constants$1814.gtk_icon_view_get_column_spacing$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_view_set_margin$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_icon_view_set_margin$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_set_margin",
        constants$1814.gtk_icon_view_set_margin$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_view_get_margin$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_view_get_margin$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_get_margin",
        constants$1814.gtk_icon_view_get_margin$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_view_set_item_padding$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_icon_view_set_item_padding$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_set_item_padding",
        constants$1814.gtk_icon_view_set_item_padding$FUNC, false
    );
}


