// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1434 {

    static final FunctionDescriptor gtk_application_is_inhibited$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_application_is_inhibited$MH = RuntimeHelper.downcallHandle(
        "gtk_application_is_inhibited",
        constants$1434.gtk_application_is_inhibited$FUNC, false
    );
    static final FunctionDescriptor gtk_application_get_window_by_id$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_application_get_window_by_id$MH = RuntimeHelper.downcallHandle(
        "gtk_application_get_window_by_id",
        constants$1434.gtk_application_get_window_by_id$FUNC, false
    );
    static final FunctionDescriptor gtk_application_get_active_window$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_application_get_active_window$MH = RuntimeHelper.downcallHandle(
        "gtk_application_get_active_window",
        constants$1434.gtk_application_get_active_window$FUNC, false
    );
    static final FunctionDescriptor gtk_application_list_action_descriptions$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_application_list_action_descriptions$MH = RuntimeHelper.downcallHandle(
        "gtk_application_list_action_descriptions",
        constants$1434.gtk_application_list_action_descriptions$FUNC, false
    );
    static final FunctionDescriptor gtk_application_get_accels_for_action$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_application_get_accels_for_action$MH = RuntimeHelper.downcallHandle(
        "gtk_application_get_accels_for_action",
        constants$1434.gtk_application_get_accels_for_action$FUNC, false
    );
    static final FunctionDescriptor gtk_application_get_actions_for_accel$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_application_get_actions_for_accel$MH = RuntimeHelper.downcallHandle(
        "gtk_application_get_actions_for_accel",
        constants$1434.gtk_application_get_actions_for_accel$FUNC, false
    );
}


