// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$795 {

    static final FunctionDescriptor g_simple_async_result_get_source_tag$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_simple_async_result_get_source_tag$MH = RuntimeHelper.downcallHandle(
        "g_simple_async_result_get_source_tag",
        constants$795.g_simple_async_result_get_source_tag$FUNC, false
    );
    static final FunctionDescriptor g_simple_async_result_set_handle_cancellation$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_simple_async_result_set_handle_cancellation$MH = RuntimeHelper.downcallHandle(
        "g_simple_async_result_set_handle_cancellation",
        constants$795.g_simple_async_result_set_handle_cancellation$FUNC, false
    );
    static final FunctionDescriptor g_simple_async_result_complete$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_simple_async_result_complete$MH = RuntimeHelper.downcallHandle(
        "g_simple_async_result_complete",
        constants$795.g_simple_async_result_complete$FUNC, false
    );
    static final FunctionDescriptor g_simple_async_result_complete_in_idle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_simple_async_result_complete_in_idle$MH = RuntimeHelper.downcallHandle(
        "g_simple_async_result_complete_in_idle",
        constants$795.g_simple_async_result_complete_in_idle$FUNC, false
    );
    static final FunctionDescriptor g_simple_async_result_run_in_thread$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_simple_async_result_run_in_thread$MH = RuntimeHelper.downcallHandle(
        "g_simple_async_result_run_in_thread",
        constants$795.g_simple_async_result_run_in_thread$FUNC, false
    );
    static final FunctionDescriptor g_simple_async_result_set_from_error$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_simple_async_result_set_from_error$MH = RuntimeHelper.downcallHandle(
        "g_simple_async_result_set_from_error",
        constants$795.g_simple_async_result_set_from_error$FUNC, false
    );
}


