// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$761 {

    static final FunctionDescriptor g_permission_get_can_acquire$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_permission_get_can_acquire$MH = RuntimeHelper.downcallHandle(
        "g_permission_get_can_acquire",
        constants$761.g_permission_get_can_acquire$FUNC, false
    );
    static final FunctionDescriptor g_permission_get_can_release$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_permission_get_can_release$MH = RuntimeHelper.downcallHandle(
        "g_permission_get_can_release",
        constants$761.g_permission_get_can_release$FUNC, false
    );
    static final FunctionDescriptor g_permission_impl_update$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_permission_impl_update$MH = RuntimeHelper.downcallHandle(
        "g_permission_impl_update",
        constants$761.g_permission_impl_update$FUNC, false
    );
    static final FunctionDescriptor g_pollable_input_stream_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_pollable_input_stream_get_type$MH = RuntimeHelper.downcallHandle(
        "g_pollable_input_stream_get_type",
        constants$761.g_pollable_input_stream_get_type$FUNC, false
    );
    static final FunctionDescriptor g_pollable_input_stream_can_poll$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_pollable_input_stream_can_poll$MH = RuntimeHelper.downcallHandle(
        "g_pollable_input_stream_can_poll",
        constants$761.g_pollable_input_stream_can_poll$FUNC, false
    );
    static final FunctionDescriptor g_pollable_input_stream_is_readable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_pollable_input_stream_is_readable$MH = RuntimeHelper.downcallHandle(
        "g_pollable_input_stream_is_readable",
        constants$761.g_pollable_input_stream_is_readable$FUNC, false
    );
}


