// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2091 {

    static final FunctionDescriptor gtk_font_selection_get_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_selection_get_size$MH = RuntimeHelper.downcallHandle(
        "gtk_font_selection_get_size",
        constants$2091.gtk_font_selection_get_size$FUNC, false
    );
    static final FunctionDescriptor gtk_font_selection_get_font_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_selection_get_font_name$MH = RuntimeHelper.downcallHandle(
        "gtk_font_selection_get_font_name",
        constants$2091.gtk_font_selection_get_font_name$FUNC, false
    );
    static final FunctionDescriptor gtk_font_selection_set_font_name$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_selection_set_font_name$MH = RuntimeHelper.downcallHandle(
        "gtk_font_selection_set_font_name",
        constants$2091.gtk_font_selection_set_font_name$FUNC, false
    );
    static final FunctionDescriptor gtk_font_selection_get_preview_text$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_selection_get_preview_text$MH = RuntimeHelper.downcallHandle(
        "gtk_font_selection_get_preview_text",
        constants$2091.gtk_font_selection_get_preview_text$FUNC, false
    );
    static final FunctionDescriptor gtk_font_selection_set_preview_text$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_selection_set_preview_text$MH = RuntimeHelper.downcallHandle(
        "gtk_font_selection_set_preview_text",
        constants$2091.gtk_font_selection_set_preview_text$FUNC, false
    );
    static final FunctionDescriptor gtk_font_selection_dialog_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_font_selection_dialog_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_font_selection_dialog_get_type",
        constants$2091.gtk_font_selection_dialog_get_type$FUNC, false
    );
}


