// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1927 {

    static final FunctionDescriptor gtk_range_get_adjustment$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_range_get_adjustment$MH = RuntimeHelper.downcallHandle(
        "gtk_range_get_adjustment",
        constants$1927.gtk_range_get_adjustment$FUNC, false
    );
    static final FunctionDescriptor gtk_range_set_inverted$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_range_set_inverted$MH = RuntimeHelper.downcallHandle(
        "gtk_range_set_inverted",
        constants$1927.gtk_range_set_inverted$FUNC, false
    );
    static final FunctionDescriptor gtk_range_get_inverted$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_range_get_inverted$MH = RuntimeHelper.downcallHandle(
        "gtk_range_get_inverted",
        constants$1927.gtk_range_get_inverted$FUNC, false
    );
    static final FunctionDescriptor gtk_range_set_flippable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_range_set_flippable$MH = RuntimeHelper.downcallHandle(
        "gtk_range_set_flippable",
        constants$1927.gtk_range_set_flippable$FUNC, false
    );
    static final FunctionDescriptor gtk_range_get_flippable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_range_get_flippable$MH = RuntimeHelper.downcallHandle(
        "gtk_range_get_flippable",
        constants$1927.gtk_range_get_flippable$FUNC, false
    );
    static final FunctionDescriptor gtk_range_set_slider_size_fixed$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_range_set_slider_size_fixed$MH = RuntimeHelper.downcallHandle(
        "gtk_range_set_slider_size_fixed",
        constants$1927.gtk_range_set_slider_size_fixed$FUNC, false
    );
}


