// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2062 {

    static final FunctionDescriptor gtk_widget_path_append_type$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle gtk_widget_path_append_type$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_path_append_type",
        constants$2062.gtk_widget_path_append_type$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_path_prepend_type$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle gtk_widget_path_prepend_type$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_path_prepend_type",
        constants$2062.gtk_widget_path_prepend_type$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_path_append_with_siblings$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_path_append_with_siblings$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_path_append_with_siblings",
        constants$2062.gtk_widget_path_append_with_siblings$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_path_append_for_widget$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_path_append_for_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_path_append_for_widget",
        constants$2062.gtk_widget_path_append_for_widget$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_path_iter_get_object_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_path_iter_get_object_type$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_path_iter_get_object_type",
        constants$2062.gtk_widget_path_iter_get_object_type$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_path_iter_set_object_type$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle gtk_widget_path_iter_set_object_type$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_path_iter_set_object_type",
        constants$2062.gtk_widget_path_iter_set_object_type$FUNC, false
    );
}


