// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$653 {

    static final FunctionDescriptor g_file_equal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_equal$MH = RuntimeHelper.downcallHandle(
        "g_file_equal",
        constants$653.g_file_equal$FUNC, false
    );
    static final FunctionDescriptor g_file_get_basename$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_get_basename$MH = RuntimeHelper.downcallHandle(
        "g_file_get_basename",
        constants$653.g_file_get_basename$FUNC, false
    );
    static final FunctionDescriptor g_file_get_path$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_get_path$MH = RuntimeHelper.downcallHandle(
        "g_file_get_path",
        constants$653.g_file_get_path$FUNC, false
    );
    static final FunctionDescriptor g_file_peek_path$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_peek_path$MH = RuntimeHelper.downcallHandle(
        "g_file_peek_path",
        constants$653.g_file_peek_path$FUNC, false
    );
    static final FunctionDescriptor g_file_get_uri$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_get_uri$MH = RuntimeHelper.downcallHandle(
        "g_file_get_uri",
        constants$653.g_file_get_uri$FUNC, false
    );
    static final FunctionDescriptor g_file_get_parse_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_get_parse_name$MH = RuntimeHelper.downcallHandle(
        "g_file_get_parse_name",
        constants$653.g_file_get_parse_name$FUNC, false
    );
}


