// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1410 {

    static final FunctionDescriptor gtk_widget_set_opacity$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle gtk_widget_set_opacity$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_opacity",
        constants$1410.gtk_widget_set_opacity$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_get_opacity$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_opacity$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_opacity",
        constants$1410.gtk_widget_get_opacity$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_set_device_enabled$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_device_enabled$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_device_enabled",
        constants$1410.gtk_widget_set_device_enabled$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_get_device_enabled$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_device_enabled$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_device_enabled",
        constants$1410.gtk_widget_get_device_enabled$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_get_toplevel$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_toplevel$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_toplevel",
        constants$1410.gtk_widget_get_toplevel$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_get_ancestor$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle gtk_widget_get_ancestor$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_ancestor",
        constants$1410.gtk_widget_get_ancestor$FUNC, false
    );
}


