// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1422 {

    static final FunctionDescriptor gtk_widget_class_list_style_properties$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_class_list_style_properties$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_class_list_style_properties",
        constants$1422.gtk_widget_class_list_style_properties$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_style_get_property$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_style_get_property$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_style_get_property",
        constants$1422.gtk_widget_style_get_property$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_style_get_valist$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_style_get_valist$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_style_get_valist",
        constants$1422.gtk_widget_style_get_valist$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_style_get$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_style_get$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_style_get",
        constants$1422.gtk_widget_style_get$FUNC, true
    );
    static final FunctionDescriptor gtk_widget_set_direction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_direction$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_direction",
        constants$1422.gtk_widget_set_direction$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_get_direction$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_direction$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_direction",
        constants$1422.gtk_widget_get_direction$FUNC, false
    );
}


