// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1644 {

    static final FunctionDescriptor gtk_app_chooser_button_set_active_custom_item$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_app_chooser_button_set_active_custom_item$MH = RuntimeHelper.downcallHandle(
        "gtk_app_chooser_button_set_active_custom_item",
        constants$1644.gtk_app_chooser_button_set_active_custom_item$FUNC, false
    );
    static final FunctionDescriptor gtk_app_chooser_button_set_show_dialog_item$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_app_chooser_button_set_show_dialog_item$MH = RuntimeHelper.downcallHandle(
        "gtk_app_chooser_button_set_show_dialog_item",
        constants$1644.gtk_app_chooser_button_set_show_dialog_item$FUNC, false
    );
    static final FunctionDescriptor gtk_app_chooser_button_get_show_dialog_item$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_app_chooser_button_get_show_dialog_item$MH = RuntimeHelper.downcallHandle(
        "gtk_app_chooser_button_get_show_dialog_item",
        constants$1644.gtk_app_chooser_button_get_show_dialog_item$FUNC, false
    );
    static final FunctionDescriptor gtk_app_chooser_button_set_heading$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_app_chooser_button_set_heading$MH = RuntimeHelper.downcallHandle(
        "gtk_app_chooser_button_set_heading",
        constants$1644.gtk_app_chooser_button_set_heading$FUNC, false
    );
    static final FunctionDescriptor gtk_app_chooser_button_get_heading$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_app_chooser_button_get_heading$MH = RuntimeHelper.downcallHandle(
        "gtk_app_chooser_button_get_heading",
        constants$1644.gtk_app_chooser_button_get_heading$FUNC, false
    );
    static final FunctionDescriptor gtk_app_chooser_button_set_show_default_item$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_app_chooser_button_set_show_default_item$MH = RuntimeHelper.downcallHandle(
        "gtk_app_chooser_button_set_show_default_item",
        constants$1644.gtk_app_chooser_button_set_show_default_item$FUNC, false
    );
}


