// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1063 {

    static final FunctionDescriptor pango_get_log_attrs$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pango_get_log_attrs$MH = RuntimeHelper.downcallHandle(
        "pango_get_log_attrs",
        constants$1063.pango_get_log_attrs$FUNC, false
    );
    static final FunctionDescriptor pango_default_break$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pango_default_break$MH = RuntimeHelper.downcallHandle(
        "pango_default_break",
        constants$1063.pango_default_break$FUNC, false
    );
    static final FunctionDescriptor pango_tailor_break$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pango_tailor_break$MH = RuntimeHelper.downcallHandle(
        "pango_tailor_break",
        constants$1063.pango_tailor_break$FUNC, false
    );
    static final FunctionDescriptor pango_fontset_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle pango_fontset_get_type$MH = RuntimeHelper.downcallHandle(
        "pango_fontset_get_type",
        constants$1063.pango_fontset_get_type$FUNC, false
    );
    static final FunctionDescriptor PangoFontsetForeachFunc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle PangoFontsetForeachFunc$MH = RuntimeHelper.downcallHandle(
        constants$1063.PangoFontsetForeachFunc$FUNC, false
    );
}


