// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2090 {

    static final FunctionDescriptor gtk_font_selection_get_face_list$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_selection_get_face_list$MH = RuntimeHelper.downcallHandle(
        "gtk_font_selection_get_face_list",
        constants$2090.gtk_font_selection_get_face_list$FUNC, false
    );
    static final FunctionDescriptor gtk_font_selection_get_size_entry$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_selection_get_size_entry$MH = RuntimeHelper.downcallHandle(
        "gtk_font_selection_get_size_entry",
        constants$2090.gtk_font_selection_get_size_entry$FUNC, false
    );
    static final FunctionDescriptor gtk_font_selection_get_size_list$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_selection_get_size_list$MH = RuntimeHelper.downcallHandle(
        "gtk_font_selection_get_size_list",
        constants$2090.gtk_font_selection_get_size_list$FUNC, false
    );
    static final FunctionDescriptor gtk_font_selection_get_preview_entry$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_selection_get_preview_entry$MH = RuntimeHelper.downcallHandle(
        "gtk_font_selection_get_preview_entry",
        constants$2090.gtk_font_selection_get_preview_entry$FUNC, false
    );
    static final FunctionDescriptor gtk_font_selection_get_family$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_selection_get_family$MH = RuntimeHelper.downcallHandle(
        "gtk_font_selection_get_family",
        constants$2090.gtk_font_selection_get_family$FUNC, false
    );
    static final FunctionDescriptor gtk_font_selection_get_face$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_font_selection_get_face$MH = RuntimeHelper.downcallHandle(
        "gtk_font_selection_get_face",
        constants$2090.gtk_font_selection_get_face$FUNC, false
    );
}


