// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$304 {

    static final FunctionDescriptor g_string_chunk_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_string_chunk_free$MH = RuntimeHelper.downcallHandle(
        "g_string_chunk_free",
        constants$304.g_string_chunk_free$FUNC, false
    );
    static final FunctionDescriptor g_string_chunk_clear$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_string_chunk_clear$MH = RuntimeHelper.downcallHandle(
        "g_string_chunk_clear",
        constants$304.g_string_chunk_clear$FUNC, false
    );
    static final FunctionDescriptor g_string_chunk_insert$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_string_chunk_insert$MH = RuntimeHelper.downcallHandle(
        "g_string_chunk_insert",
        constants$304.g_string_chunk_insert$FUNC, false
    );
    static final FunctionDescriptor g_string_chunk_insert_len$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_string_chunk_insert_len$MH = RuntimeHelper.downcallHandle(
        "g_string_chunk_insert_len",
        constants$304.g_string_chunk_insert_len$FUNC, false
    );
    static final FunctionDescriptor g_string_chunk_insert_const$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_string_chunk_insert_const$MH = RuntimeHelper.downcallHandle(
        "g_string_chunk_insert_const",
        constants$304.g_string_chunk_insert_const$FUNC, false
    );
    static final FunctionDescriptor g_strv_builder_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle g_strv_builder_new$MH = RuntimeHelper.downcallHandle(
        "g_strv_builder_new",
        constants$304.g_strv_builder_new$FUNC, false
    );
}


