// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2082 {

    static final FunctionDescriptor gtk_action_group_add_radio_actions$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_action_group_add_radio_actions$MH = RuntimeHelper.downcallHandle(
        "gtk_action_group_add_radio_actions",
        constants$2082.gtk_action_group_add_radio_actions$FUNC, false
    );
    static final FunctionDescriptor gtk_action_group_add_actions_full$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_action_group_add_actions_full$MH = RuntimeHelper.downcallHandle(
        "gtk_action_group_add_actions_full",
        constants$2082.gtk_action_group_add_actions_full$FUNC, false
    );
    static final FunctionDescriptor gtk_action_group_add_toggle_actions_full$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_action_group_add_toggle_actions_full$MH = RuntimeHelper.downcallHandle(
        "gtk_action_group_add_toggle_actions_full",
        constants$2082.gtk_action_group_add_toggle_actions_full$FUNC, false
    );
    static final FunctionDescriptor gtk_action_group_add_radio_actions_full$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_action_group_add_radio_actions_full$MH = RuntimeHelper.downcallHandle(
        "gtk_action_group_add_radio_actions_full",
        constants$2082.gtk_action_group_add_radio_actions_full$FUNC, false
    );
    static final FunctionDescriptor gtk_action_group_set_translate_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_action_group_set_translate_func$MH = RuntimeHelper.downcallHandle(
        "gtk_action_group_set_translate_func",
        constants$2082.gtk_action_group_set_translate_func$FUNC, false
    );
    static final FunctionDescriptor gtk_action_group_set_translation_domain$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_action_group_set_translation_domain$MH = RuntimeHelper.downcallHandle(
        "gtk_action_group_set_translation_domain",
        constants$2082.gtk_action_group_set_translation_domain$FUNC, false
    );
}


