// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1472 {

    static final FunctionDescriptor gtk_about_dialog_get_comments$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_about_dialog_get_comments$MH = RuntimeHelper.downcallHandle(
        "gtk_about_dialog_get_comments",
        constants$1472.gtk_about_dialog_get_comments$FUNC, false
    );
    static final FunctionDescriptor gtk_about_dialog_set_comments$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_about_dialog_set_comments$MH = RuntimeHelper.downcallHandle(
        "gtk_about_dialog_set_comments",
        constants$1472.gtk_about_dialog_set_comments$FUNC, false
    );
    static final FunctionDescriptor gtk_about_dialog_get_license$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_about_dialog_get_license$MH = RuntimeHelper.downcallHandle(
        "gtk_about_dialog_get_license",
        constants$1472.gtk_about_dialog_get_license$FUNC, false
    );
    static final FunctionDescriptor gtk_about_dialog_set_license$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_about_dialog_set_license$MH = RuntimeHelper.downcallHandle(
        "gtk_about_dialog_set_license",
        constants$1472.gtk_about_dialog_set_license$FUNC, false
    );
    static final FunctionDescriptor gtk_about_dialog_set_license_type$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_about_dialog_set_license_type$MH = RuntimeHelper.downcallHandle(
        "gtk_about_dialog_set_license_type",
        constants$1472.gtk_about_dialog_set_license_type$FUNC, false
    );
    static final FunctionDescriptor gtk_about_dialog_get_license_type$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_about_dialog_get_license_type$MH = RuntimeHelper.downcallHandle(
        "gtk_about_dialog_get_license_type",
        constants$1472.gtk_about_dialog_get_license_type$FUNC, false
    );
}


