// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1455 {

    static final FunctionDescriptor gtk_window_set_icon_from_file$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_set_icon_from_file$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_icon_from_file",
        constants$1455.gtk_window_set_icon_from_file$FUNC, false
    );
    static final FunctionDescriptor gtk_window_get_icon$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_icon$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_icon",
        constants$1455.gtk_window_get_icon$FUNC, false
    );
    static final FunctionDescriptor gtk_window_get_icon_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_icon_name$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_icon_name",
        constants$1455.gtk_window_get_icon_name$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_default_icon_list$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_set_default_icon_list$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_default_icon_list",
        constants$1455.gtk_window_set_default_icon_list$FUNC, false
    );
    static final FunctionDescriptor gtk_window_get_default_icon_list$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_window_get_default_icon_list$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_default_icon_list",
        constants$1455.gtk_window_get_default_icon_list$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_default_icon$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_set_default_icon$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_default_icon",
        constants$1455.gtk_window_set_default_icon$FUNC, false
    );
}


