// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$727 {

    static final FunctionDescriptor glib_slistautoptr_cleanup_GListStoreClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GListStoreClass$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GListStoreClass",
        constants$727.glib_slistautoptr_cleanup_GListStoreClass$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GListStoreClass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GListStoreClass$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GListStoreClass",
        constants$727.glib_queueautoptr_cleanup_GListStoreClass$FUNC, false
    );
    static final FunctionDescriptor G_LIST_STORE$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle G_LIST_STORE$MH = RuntimeHelper.downcallHandle(
        "G_LIST_STORE",
        constants$727.G_LIST_STORE$FUNC, false
    );
    static final FunctionDescriptor G_IS_LIST_STORE$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle G_IS_LIST_STORE$MH = RuntimeHelper.downcallHandle(
        "G_IS_LIST_STORE",
        constants$727.G_IS_LIST_STORE$FUNC, false
    );
    static final FunctionDescriptor g_list_store_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_list_store_new$MH = RuntimeHelper.downcallHandle(
        "g_list_store_new",
        constants$727.g_list_store_new$FUNC, false
    );
    static final FunctionDescriptor g_list_store_insert$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_list_store_insert$MH = RuntimeHelper.downcallHandle(
        "g_list_store_insert",
        constants$727.g_list_store_insert$FUNC, false
    );
}


