// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2135 {

    static final FunctionDescriptor gtk_theming_engine_get_margin$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_theming_engine_get_margin$MH = RuntimeHelper.downcallHandle(
        "gtk_theming_engine_get_margin",
        constants$2135.gtk_theming_engine_get_margin$FUNC, false
    );
    static final FunctionDescriptor gtk_theming_engine_get_font$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_theming_engine_get_font$MH = RuntimeHelper.downcallHandle(
        "gtk_theming_engine_get_font",
        constants$2135.gtk_theming_engine_get_font$FUNC, false
    );
    static final FunctionDescriptor gtk_theming_engine_load$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_theming_engine_load$MH = RuntimeHelper.downcallHandle(
        "gtk_theming_engine_load",
        constants$2135.gtk_theming_engine_load$FUNC, false
    );
    static final FunctionDescriptor gtk_theming_engine_get_screen$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_theming_engine_get_screen$MH = RuntimeHelper.downcallHandle(
        "gtk_theming_engine_get_screen",
        constants$2135.gtk_theming_engine_get_screen$FUNC, false
    );
    static final FunctionDescriptor gtk_ui_manager_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_ui_manager_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_ui_manager_get_type",
        constants$2135.gtk_ui_manager_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_ui_manager_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_ui_manager_new$MH = RuntimeHelper.downcallHandle(
        "gtk_ui_manager_new",
        constants$2135.gtk_ui_manager_new$FUNC, false
    );
}


