// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$223 {

    static final FunctionDescriptor g_variant_dup_strv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_dup_strv$MH = RuntimeHelper.downcallHandle(
        "g_variant_dup_strv",
        constants$223.g_variant_dup_strv$FUNC, false
    );
    static final FunctionDescriptor g_variant_get_objv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_get_objv$MH = RuntimeHelper.downcallHandle(
        "g_variant_get_objv",
        constants$223.g_variant_get_objv$FUNC, false
    );
    static final FunctionDescriptor g_variant_dup_objv$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_dup_objv$MH = RuntimeHelper.downcallHandle(
        "g_variant_dup_objv",
        constants$223.g_variant_dup_objv$FUNC, false
    );
    static final FunctionDescriptor g_variant_get_bytestring$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_get_bytestring$MH = RuntimeHelper.downcallHandle(
        "g_variant_get_bytestring",
        constants$223.g_variant_get_bytestring$FUNC, false
    );
    static final FunctionDescriptor g_variant_dup_bytestring$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_dup_bytestring$MH = RuntimeHelper.downcallHandle(
        "g_variant_dup_bytestring",
        constants$223.g_variant_dup_bytestring$FUNC, false
    );
    static final FunctionDescriptor g_variant_get_bytestring_array$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_variant_get_bytestring_array$MH = RuntimeHelper.downcallHandle(
        "g_variant_get_bytestring_array",
        constants$223.g_variant_get_bytestring_array$FUNC, false
    );
}


