// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2131 {

    static final FunctionDescriptor gtk_table_get_size$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_table_get_size$MH = RuntimeHelper.downcallHandle(
        "gtk_table_get_size",
        constants$2131.gtk_table_get_size$FUNC, false
    );
    static final FunctionDescriptor gtk_tearoff_menu_item_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_tearoff_menu_item_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_tearoff_menu_item_get_type",
        constants$2131.gtk_tearoff_menu_item_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_tearoff_menu_item_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_tearoff_menu_item_new$MH = RuntimeHelper.downcallHandle(
        "gtk_tearoff_menu_item_new",
        constants$2131.gtk_tearoff_menu_item_new$FUNC, false
    );
    static final FunctionDescriptor gtk_theming_engine_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_theming_engine_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_theming_engine_get_type",
        constants$2131.gtk_theming_engine_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_theming_engine_register_property$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_theming_engine_register_property$MH = RuntimeHelper.downcallHandle(
        "gtk_theming_engine_register_property",
        constants$2131.gtk_theming_engine_register_property$FUNC, false
    );
    static final FunctionDescriptor gtk_theming_engine_get_property$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_theming_engine_get_property$MH = RuntimeHelper.downcallHandle(
        "gtk_theming_engine_get_property",
        constants$2131.gtk_theming_engine_get_property$FUNC, false
    );
}


