// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1227 {

    static final FunctionDescriptor gdk_window_enable_synchronized_configure$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_enable_synchronized_configure$MH = RuntimeHelper.downcallHandle(
        "gdk_window_enable_synchronized_configure",
        constants$1227.gdk_window_enable_synchronized_configure$FUNC, false
    );
    static final FunctionDescriptor gdk_window_configure_finished$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_configure_finished$MH = RuntimeHelper.downcallHandle(
        "gdk_window_configure_finished",
        constants$1227.gdk_window_configure_finished$FUNC, false
    );
    static final FunctionDescriptor gdk_get_default_root_window$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gdk_get_default_root_window$MH = RuntimeHelper.downcallHandle(
        "gdk_get_default_root_window",
        constants$1227.gdk_get_default_root_window$FUNC, false
    );
    static final FunctionDescriptor gdk_offscreen_window_get_surface$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_offscreen_window_get_surface$MH = RuntimeHelper.downcallHandle(
        "gdk_offscreen_window_get_surface",
        constants$1227.gdk_offscreen_window_get_surface$FUNC, false
    );
    static final FunctionDescriptor gdk_offscreen_window_set_embedder$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_offscreen_window_set_embedder$MH = RuntimeHelper.downcallHandle(
        "gdk_offscreen_window_set_embedder",
        constants$1227.gdk_offscreen_window_set_embedder$FUNC, false
    );
    static final FunctionDescriptor gdk_offscreen_window_get_embedder$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_offscreen_window_get_embedder$MH = RuntimeHelper.downcallHandle(
        "gdk_offscreen_window_get_embedder",
        constants$1227.gdk_offscreen_window_get_embedder$FUNC, false
    );
}


