// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1765 {

    static final FunctionDescriptor gtk_gesture_long_press_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_gesture_long_press_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_long_press_get_type",
        constants$1765.gtk_gesture_long_press_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_gesture_long_press_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_gesture_long_press_new$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_long_press_new",
        constants$1765.gtk_gesture_long_press_new$FUNC, false
    );
    static final FunctionDescriptor gtk_gesture_multi_press_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_gesture_multi_press_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_multi_press_get_type",
        constants$1765.gtk_gesture_multi_press_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_gesture_multi_press_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_gesture_multi_press_new$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_multi_press_new",
        constants$1765.gtk_gesture_multi_press_new$FUNC, false
    );
    static final FunctionDescriptor gtk_gesture_multi_press_set_area$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_gesture_multi_press_set_area$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_multi_press_set_area",
        constants$1765.gtk_gesture_multi_press_set_area$FUNC, false
    );
    static final FunctionDescriptor gtk_gesture_multi_press_get_area$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_gesture_multi_press_get_area$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_multi_press_get_area",
        constants$1765.gtk_gesture_multi_press_get_area$FUNC, false
    );
}


