// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2337 {

    static final MemorySegment GTK_STYLE_CLASS_HEADER$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("header");
    static final MemorySegment GTK_STYLE_CLASS_ACCELERATOR$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("accelerator");
    static final MemorySegment GTK_STYLE_CLASS_RAISED$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("raised");
    static final MemorySegment GTK_STYLE_CLASS_LINKED$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("linked");
    static final MemorySegment GTK_STYLE_CLASS_GRIP$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("grip");
    static final MemorySegment GTK_STYLE_CLASS_DOCK$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("dock");
}


