// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1824 {

    static final FunctionDescriptor gtk_info_bar_add_buttons$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_info_bar_add_buttons$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_add_buttons",
        constants$1824.gtk_info_bar_add_buttons$FUNC, true
    );
    static final FunctionDescriptor gtk_info_bar_set_response_sensitive$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_info_bar_set_response_sensitive$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_set_response_sensitive",
        constants$1824.gtk_info_bar_set_response_sensitive$FUNC, false
    );
    static final FunctionDescriptor gtk_info_bar_set_default_response$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_info_bar_set_default_response$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_set_default_response",
        constants$1824.gtk_info_bar_set_default_response$FUNC, false
    );
    static final FunctionDescriptor gtk_info_bar_response$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_info_bar_response$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_response",
        constants$1824.gtk_info_bar_response$FUNC, false
    );
    static final FunctionDescriptor gtk_info_bar_set_message_type$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_info_bar_set_message_type$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_set_message_type",
        constants$1824.gtk_info_bar_set_message_type$FUNC, false
    );
    static final FunctionDescriptor gtk_info_bar_get_message_type$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_info_bar_get_message_type$MH = RuntimeHelper.downcallHandle(
        "gtk_info_bar_get_message_type",
        constants$1824.gtk_info_bar_get_message_type$FUNC, false
    );
}


