// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2055 {

    static final FunctionDescriptor gtk_revealer_transition_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_revealer_transition_type_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_revealer_transition_type_get_type",
        constants$2055.gtk_revealer_transition_type_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_corner_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_corner_type_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_corner_type_get_type",
        constants$2055.gtk_corner_type_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_policy_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_policy_type_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_policy_type_get_type",
        constants$2055.gtk_policy_type_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_target_flags_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_target_flags_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_target_flags_get_type",
        constants$2055.gtk_target_flags_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_shortcut_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_shortcut_type_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_shortcut_type_get_type",
        constants$2055.gtk_shortcut_type_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_spin_button_update_policy_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_spin_button_update_policy_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_spin_button_update_policy_get_type",
        constants$2055.gtk_spin_button_update_policy_get_type$FUNC, false
    );
}


