// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$462 {

    static final FunctionDescriptor g_checksum_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_checksum_get_type$MH = RuntimeHelper.downcallHandle(
        "g_checksum_get_type",
        constants$462.g_checksum_get_type$FUNC, false
    );
    static final FunctionDescriptor g_markup_parse_context_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_markup_parse_context_get_type$MH = RuntimeHelper.downcallHandle(
        "g_markup_parse_context_get_type",
        constants$462.g_markup_parse_context_get_type$FUNC, false
    );
    static final FunctionDescriptor g_mapped_file_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_mapped_file_get_type$MH = RuntimeHelper.downcallHandle(
        "g_mapped_file_get_type",
        constants$462.g_mapped_file_get_type$FUNC, false
    );
    static final FunctionDescriptor g_option_group_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_option_group_get_type$MH = RuntimeHelper.downcallHandle(
        "g_option_group_get_type",
        constants$462.g_option_group_get_type$FUNC, false
    );
    static final FunctionDescriptor g_uri_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_uri_get_type$MH = RuntimeHelper.downcallHandle(
        "g_uri_get_type",
        constants$462.g_uri_get_type$FUNC, false
    );
    static final FunctionDescriptor g_tree_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_tree_get_type$MH = RuntimeHelper.downcallHandle(
        "g_tree_get_type",
        constants$462.g_tree_get_type$FUNC, false
    );
}


