// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2262 {

    static final FunctionDescriptor glib_autoptr_cleanup_GtkTextMark$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkTextMark$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkTextMark",
        constants$2262.glib_autoptr_cleanup_GtkTextMark$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkTextMark$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkTextMark$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkTextMark",
        constants$2262.glib_listautoptr_cleanup_GtkTextMark$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkTextMark$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkTextMark$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkTextMark",
        constants$2262.glib_slistautoptr_cleanup_GtkTextMark$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkTextMark$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkTextMark$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkTextMark",
        constants$2262.glib_queueautoptr_cleanup_GtkTextMark$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkTextTag$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkTextTag$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkTextTag",
        constants$2262.glib_autoptr_clear_GtkTextTag$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkTextTag$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkTextTag$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkTextTag",
        constants$2262.glib_autoptr_cleanup_GtkTextTag$FUNC, false
    );
}


