// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2036 {

    static final FunctionDescriptor gtk_tree_store_insert$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tree_store_insert$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_insert",
        constants$2036.gtk_tree_store_insert$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_store_insert_before$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_store_insert_before$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_insert_before",
        constants$2036.gtk_tree_store_insert_before$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_store_insert_after$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_store_insert_after$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_insert_after",
        constants$2036.gtk_tree_store_insert_after$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_store_insert_with_values$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tree_store_insert_with_values$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_insert_with_values",
        constants$2036.gtk_tree_store_insert_with_values$FUNC, true
    );
    static final FunctionDescriptor gtk_tree_store_insert_with_valuesv$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tree_store_insert_with_valuesv$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_insert_with_valuesv",
        constants$2036.gtk_tree_store_insert_with_valuesv$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_store_prepend$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_store_prepend$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_store_prepend",
        constants$2036.gtk_tree_store_prepend$FUNC, false
    );
}


