// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2238 {

    static final FunctionDescriptor glib_listautoptr_cleanup_GtkRecentChooserWidget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkRecentChooserWidget$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkRecentChooserWidget",
        constants$2238.glib_listautoptr_cleanup_GtkRecentChooserWidget$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkRecentChooserWidget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkRecentChooserWidget$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkRecentChooserWidget",
        constants$2238.glib_slistautoptr_cleanup_GtkRecentChooserWidget$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkRecentChooserWidget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkRecentChooserWidget$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkRecentChooserWidget",
        constants$2238.glib_queueautoptr_cleanup_GtkRecentChooserWidget$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkRecentFilter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkRecentFilter$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkRecentFilter",
        constants$2238.glib_autoptr_clear_GtkRecentFilter$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkRecentFilter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkRecentFilter$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkRecentFilter",
        constants$2238.glib_autoptr_cleanup_GtkRecentFilter$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkRecentFilter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkRecentFilter$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkRecentFilter",
        constants$2238.glib_listautoptr_cleanup_GtkRecentFilter$FUNC, false
    );
}


