// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1752 {

    static final FunctionDescriptor GtkFlowBoxSortFunc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GtkFlowBoxSortFunc$MH = RuntimeHelper.downcallHandle(
        constants$1752.GtkFlowBoxSortFunc$FUNC, false
    );
    static final FunctionDescriptor gtk_flow_box_set_sort_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_flow_box_set_sort_func$MH = RuntimeHelper.downcallHandle(
        "gtk_flow_box_set_sort_func",
        constants$1752.gtk_flow_box_set_sort_func$FUNC, false
    );
    static final FunctionDescriptor gtk_flow_box_invalidate_sort$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_flow_box_invalidate_sort$MH = RuntimeHelper.downcallHandle(
        "gtk_flow_box_invalidate_sort",
        constants$1752.gtk_flow_box_invalidate_sort$FUNC, false
    );
    static final FunctionDescriptor gtk_font_button_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_font_button_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_font_button_get_type",
        constants$1752.gtk_font_button_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_font_button_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_font_button_new$MH = RuntimeHelper.downcallHandle(
        "gtk_font_button_new",
        constants$1752.gtk_font_button_new$FUNC, false
    );
}


