// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1456 {

    static final FunctionDescriptor gtk_window_set_default_icon_name$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_set_default_icon_name$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_default_icon_name",
        constants$1456.gtk_window_set_default_icon_name$FUNC, false
    );
    static final FunctionDescriptor gtk_window_get_default_icon_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_window_get_default_icon_name$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_default_icon_name",
        constants$1456.gtk_window_get_default_icon_name$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_default_icon_from_file$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_set_default_icon_from_file$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_default_icon_from_file",
        constants$1456.gtk_window_set_default_icon_from_file$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_auto_startup_notification$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_window_set_auto_startup_notification$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_auto_startup_notification",
        constants$1456.gtk_window_set_auto_startup_notification$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_modal$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_window_set_modal$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_modal",
        constants$1456.gtk_window_set_modal$FUNC, false
    );
    static final FunctionDescriptor gtk_window_get_modal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_modal$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_modal",
        constants$1456.gtk_window_get_modal$FUNC, false
    );
}


