// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1380 {

    static final FunctionDescriptor atk_table_ref_at$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle atk_table_ref_at$MH = RuntimeHelper.downcallHandle(
        "atk_table_ref_at",
        constants$1380.atk_table_ref_at$FUNC, false
    );
    static final FunctionDescriptor atk_table_get_index_at$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle atk_table_get_index_at$MH = RuntimeHelper.downcallHandle(
        "atk_table_get_index_at",
        constants$1380.atk_table_get_index_at$FUNC, false
    );
    static final FunctionDescriptor atk_table_get_column_at_index$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle atk_table_get_column_at_index$MH = RuntimeHelper.downcallHandle(
        "atk_table_get_column_at_index",
        constants$1380.atk_table_get_column_at_index$FUNC, false
    );
    static final FunctionDescriptor atk_table_get_row_at_index$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle atk_table_get_row_at_index$MH = RuntimeHelper.downcallHandle(
        "atk_table_get_row_at_index",
        constants$1380.atk_table_get_row_at_index$FUNC, false
    );
    static final FunctionDescriptor atk_table_get_n_columns$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle atk_table_get_n_columns$MH = RuntimeHelper.downcallHandle(
        "atk_table_get_n_columns",
        constants$1380.atk_table_get_n_columns$FUNC, false
    );
    static final FunctionDescriptor atk_table_get_n_rows$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle atk_table_get_n_rows$MH = RuntimeHelper.downcallHandle(
        "atk_table_get_n_rows",
        constants$1380.atk_table_get_n_rows$FUNC, false
    );
}


