// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1901 {

    static final FunctionDescriptor gtk_print_settings_get$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_settings_get$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_get",
        constants$1901.gtk_print_settings_get$FUNC, false
    );
    static final FunctionDescriptor gtk_print_settings_set$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_settings_set$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_set",
        constants$1901.gtk_print_settings_set$FUNC, false
    );
    static final FunctionDescriptor gtk_print_settings_unset$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_settings_unset$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_unset",
        constants$1901.gtk_print_settings_unset$FUNC, false
    );
    static final FunctionDescriptor gtk_print_settings_foreach$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_settings_foreach$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_foreach",
        constants$1901.gtk_print_settings_foreach$FUNC, false
    );
    static final FunctionDescriptor gtk_print_settings_get_bool$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_settings_get_bool$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_get_bool",
        constants$1901.gtk_print_settings_get_bool$FUNC, false
    );
    static final FunctionDescriptor gtk_print_settings_set_bool$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_settings_set_bool$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_set_bool",
        constants$1901.gtk_print_settings_set_bool$FUNC, false
    );
}


