// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2335 {

    static final MemorySegment GTK_STYLE_CLASS_PRIMARY_TOOLBAR$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("primary-toolbar");
    static final MemorySegment GTK_STYLE_CLASS_INLINE_TOOLBAR$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("inline-toolbar");
    static final MemorySegment GTK_STYLE_CLASS_STATUSBAR$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("statusbar");
    static final MemorySegment GTK_STYLE_CLASS_RADIO$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("radio");
    static final MemorySegment GTK_STYLE_CLASS_CHECK$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("check");
    static final MemorySegment GTK_STYLE_CLASS_DEFAULT$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("default");
}


