// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1206 {

    static final FunctionDescriptor gdk_window_add_filter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_add_filter$MH = RuntimeHelper.downcallHandle(
        "gdk_window_add_filter",
        constants$1206.gdk_window_add_filter$FUNC, false
    );
    static final FunctionDescriptor gdk_window_remove_filter$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_remove_filter$MH = RuntimeHelper.downcallHandle(
        "gdk_window_remove_filter",
        constants$1206.gdk_window_remove_filter$FUNC, false
    );
    static final FunctionDescriptor gdk_window_scroll$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_window_scroll$MH = RuntimeHelper.downcallHandle(
        "gdk_window_scroll",
        constants$1206.gdk_window_scroll$FUNC, false
    );
    static final FunctionDescriptor gdk_window_move_region$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_window_move_region$MH = RuntimeHelper.downcallHandle(
        "gdk_window_move_region",
        constants$1206.gdk_window_move_region$FUNC, false
    );
    static final FunctionDescriptor gdk_window_ensure_native$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_ensure_native$MH = RuntimeHelper.downcallHandle(
        "gdk_window_ensure_native",
        constants$1206.gdk_window_ensure_native$FUNC, false
    );
    static final FunctionDescriptor gdk_window_shape_combine_region$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_window_shape_combine_region$MH = RuntimeHelper.downcallHandle(
        "gdk_window_shape_combine_region",
        constants$1206.gdk_window_shape_combine_region$FUNC, false
    );
}


