// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2272 {

    static final FunctionDescriptor glib_autoptr_cleanup_GtkTooltip$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkTooltip$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkTooltip",
        constants$2272.glib_autoptr_cleanup_GtkTooltip$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkTooltip$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkTooltip$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkTooltip",
        constants$2272.glib_listautoptr_cleanup_GtkTooltip$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkTooltip$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkTooltip$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkTooltip",
        constants$2272.glib_slistautoptr_cleanup_GtkTooltip$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkTooltip$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkTooltip$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkTooltip",
        constants$2272.glib_queueautoptr_cleanup_GtkTooltip$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkTreeDragDest$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkTreeDragDest$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkTreeDragDest",
        constants$2272.glib_autoptr_clear_GtkTreeDragDest$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkTreeDragDest$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkTreeDragDest$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkTreeDragDest",
        constants$2272.glib_autoptr_cleanup_GtkTreeDragDest$FUNC, false
    );
}


