// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1983 {

    static final FunctionDescriptor gtk_statusbar_pop$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_statusbar_pop$MH = RuntimeHelper.downcallHandle(
        "gtk_statusbar_pop",
        constants$1983.gtk_statusbar_pop$FUNC, false
    );
    static final FunctionDescriptor gtk_statusbar_remove$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_statusbar_remove$MH = RuntimeHelper.downcallHandle(
        "gtk_statusbar_remove",
        constants$1983.gtk_statusbar_remove$FUNC, false
    );
    static final FunctionDescriptor gtk_statusbar_remove_all$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_statusbar_remove_all$MH = RuntimeHelper.downcallHandle(
        "gtk_statusbar_remove_all",
        constants$1983.gtk_statusbar_remove_all$FUNC, false
    );
    static final FunctionDescriptor gtk_statusbar_get_message_area$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_statusbar_get_message_area$MH = RuntimeHelper.downcallHandle(
        "gtk_statusbar_get_message_area",
        constants$1983.gtk_statusbar_get_message_area$FUNC, false
    );
    static final FunctionDescriptor gtk_switch_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_switch_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_switch_get_type",
        constants$1983.gtk_switch_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_switch_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_switch_new$MH = RuntimeHelper.downcallHandle(
        "gtk_switch_new",
        constants$1983.gtk_switch_new$FUNC, false
    );
}


