// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$664 {

    static final FunctionDescriptor g_file_make_directory_finish$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_make_directory_finish$MH = RuntimeHelper.downcallHandle(
        "g_file_make_directory_finish",
        constants$664.g_file_make_directory_finish$FUNC, false
    );
    static final FunctionDescriptor g_file_make_directory_with_parents$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_make_directory_with_parents$MH = RuntimeHelper.downcallHandle(
        "g_file_make_directory_with_parents",
        constants$664.g_file_make_directory_with_parents$FUNC, false
    );
    static final FunctionDescriptor g_file_make_symbolic_link$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_make_symbolic_link$MH = RuntimeHelper.downcallHandle(
        "g_file_make_symbolic_link",
        constants$664.g_file_make_symbolic_link$FUNC, false
    );
    static final FunctionDescriptor g_file_query_settable_attributes$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_query_settable_attributes$MH = RuntimeHelper.downcallHandle(
        "g_file_query_settable_attributes",
        constants$664.g_file_query_settable_attributes$FUNC, false
    );
    static final FunctionDescriptor g_file_query_writable_namespaces$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_query_writable_namespaces$MH = RuntimeHelper.downcallHandle(
        "g_file_query_writable_namespaces",
        constants$664.g_file_query_writable_namespaces$FUNC, false
    );
    static final FunctionDescriptor g_file_set_attribute$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_set_attribute$MH = RuntimeHelper.downcallHandle(
        "g_file_set_attribute",
        constants$664.g_file_set_attribute$FUNC, false
    );
}


