// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$670 {

    static final FunctionDescriptor g_file_start_mountable_finish$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_start_mountable_finish$MH = RuntimeHelper.downcallHandle(
        "g_file_start_mountable_finish",
        constants$670.g_file_start_mountable_finish$FUNC, false
    );
    static final FunctionDescriptor g_file_stop_mountable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_stop_mountable$MH = RuntimeHelper.downcallHandle(
        "g_file_stop_mountable",
        constants$670.g_file_stop_mountable$FUNC, false
    );
    static final FunctionDescriptor g_file_stop_mountable_finish$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_stop_mountable_finish$MH = RuntimeHelper.downcallHandle(
        "g_file_stop_mountable_finish",
        constants$670.g_file_stop_mountable_finish$FUNC, false
    );
    static final FunctionDescriptor g_file_poll_mountable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_poll_mountable$MH = RuntimeHelper.downcallHandle(
        "g_file_poll_mountable",
        constants$670.g_file_poll_mountable$FUNC, false
    );
    static final FunctionDescriptor g_file_poll_mountable_finish$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_poll_mountable_finish$MH = RuntimeHelper.downcallHandle(
        "g_file_poll_mountable_finish",
        constants$670.g_file_poll_mountable_finish$FUNC, false
    );
    static final FunctionDescriptor g_file_query_default_handler$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_file_query_default_handler$MH = RuntimeHelper.downcallHandle(
        "g_file_query_default_handler",
        constants$670.g_file_query_default_handler$FUNC, false
    );
}


