// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1883 {

    static final FunctionDescriptor gtk_paper_size_get_height$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_paper_size_get_height$MH = RuntimeHelper.downcallHandle(
        "gtk_paper_size_get_height",
        constants$1883.gtk_paper_size_get_height$FUNC, false
    );
    static final FunctionDescriptor gtk_paper_size_is_custom$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_paper_size_is_custom$MH = RuntimeHelper.downcallHandle(
        "gtk_paper_size_is_custom",
        constants$1883.gtk_paper_size_is_custom$FUNC, false
    );
    static final FunctionDescriptor gtk_paper_size_is_ipp$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_paper_size_is_ipp$MH = RuntimeHelper.downcallHandle(
        "gtk_paper_size_is_ipp",
        constants$1883.gtk_paper_size_is_ipp$FUNC, false
    );
    static final FunctionDescriptor gtk_paper_size_set_size$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_paper_size_set_size$MH = RuntimeHelper.downcallHandle(
        "gtk_paper_size_set_size",
        constants$1883.gtk_paper_size_set_size$FUNC, false
    );
    static final FunctionDescriptor gtk_paper_size_get_default_top_margin$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_paper_size_get_default_top_margin$MH = RuntimeHelper.downcallHandle(
        "gtk_paper_size_get_default_top_margin",
        constants$1883.gtk_paper_size_get_default_top_margin$FUNC, false
    );
    static final FunctionDescriptor gtk_paper_size_get_default_bottom_margin$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_paper_size_get_default_bottom_margin$MH = RuntimeHelper.downcallHandle(
        "gtk_paper_size_get_default_bottom_margin",
        constants$1883.gtk_paper_size_get_default_bottom_margin$FUNC, false
    );
}


