// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$112 {

    static final FunctionDescriptor seekdir$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle seekdir$MH = RuntimeHelper.downcallHandle(
        "seekdir",
        constants$112.seekdir$FUNC, false
    );
    static final FunctionDescriptor telldir$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle telldir$MH = RuntimeHelper.downcallHandle(
        "telldir",
        constants$112.telldir$FUNC, false
    );
    static final FunctionDescriptor dirfd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle dirfd$MH = RuntimeHelper.downcallHandle(
        "dirfd",
        constants$112.dirfd$FUNC, false
    );
    static final FunctionDescriptor scandir$__selector$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle scandir$__selector$MH = RuntimeHelper.downcallHandle(
        constants$112.scandir$__selector$FUNC, false
    );
    static final FunctionDescriptor scandir$__cmp$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
}


