// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1496 {

    static final FunctionDescriptor gtk_label_set_xalign$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle gtk_label_set_xalign$MH = RuntimeHelper.downcallHandle(
        "gtk_label_set_xalign",
        constants$1496.gtk_label_set_xalign$FUNC, false
    );
    static final FunctionDescriptor gtk_label_get_xalign$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_label_get_xalign$MH = RuntimeHelper.downcallHandle(
        "gtk_label_get_xalign",
        constants$1496.gtk_label_get_xalign$FUNC, false
    );
    static final FunctionDescriptor gtk_label_set_yalign$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle gtk_label_set_yalign$MH = RuntimeHelper.downcallHandle(
        "gtk_label_set_yalign",
        constants$1496.gtk_label_set_yalign$FUNC, false
    );
    static final FunctionDescriptor gtk_label_get_yalign$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_label_get_yalign$MH = RuntimeHelper.downcallHandle(
        "gtk_label_get_yalign",
        constants$1496.gtk_label_get_yalign$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkLabel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkLabel$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkLabel",
        constants$1496.glib_autoptr_clear_GtkLabel$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkLabel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkLabel$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkLabel",
        constants$1496.glib_autoptr_cleanup_GtkLabel$FUNC, false
    );
}


