// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2264 {

    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkTextTagTable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkTextTagTable$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkTextTagTable",
        constants$2264.glib_slistautoptr_cleanup_GtkTextTagTable$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkTextTagTable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkTextTagTable$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkTextTagTable",
        constants$2264.glib_queueautoptr_cleanup_GtkTextTagTable$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkTextView$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkTextView$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkTextView",
        constants$2264.glib_autoptr_clear_GtkTextView$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkTextView$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkTextView$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkTextView",
        constants$2264.glib_autoptr_cleanup_GtkTextView$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkTextView$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkTextView$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkTextView",
        constants$2264.glib_listautoptr_cleanup_GtkTextView$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkTextView$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkTextView$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkTextView",
        constants$2264.glib_slistautoptr_cleanup_GtkTextView$FUNC, false
    );
}


