// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1196 {

    static final FunctionDescriptor gdk_event_get_device_tool$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_event_get_device_tool$MH = RuntimeHelper.downcallHandle(
        "gdk_event_get_device_tool",
        constants$1196.gdk_event_get_device_tool$FUNC, false
    );
    static final FunctionDescriptor gdk_event_set_device_tool$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_event_set_device_tool$MH = RuntimeHelper.downcallHandle(
        "gdk_event_set_device_tool",
        constants$1196.gdk_event_set_device_tool$FUNC, false
    );
    static final FunctionDescriptor gdk_event_get_scancode$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_event_get_scancode$MH = RuntimeHelper.downcallHandle(
        "gdk_event_get_scancode",
        constants$1196.gdk_event_get_scancode$FUNC, false
    );
    static final FunctionDescriptor gdk_event_get_pointer_emulated$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_event_get_pointer_emulated$MH = RuntimeHelper.downcallHandle(
        "gdk_event_get_pointer_emulated",
        constants$1196.gdk_event_get_pointer_emulated$FUNC, false
    );
    static final FunctionDescriptor gdk_device_manager_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_device_manager_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_device_manager_get_type",
        constants$1196.gdk_device_manager_get_type$FUNC, false
    );
    static final FunctionDescriptor gdk_device_manager_get_display$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_device_manager_get_display$MH = RuntimeHelper.downcallHandle(
        "gdk_device_manager_get_display",
        constants$1196.gdk_device_manager_get_display$FUNC, false
    );
}


