// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$650 {

    static final FunctionDescriptor g_emblem_get_icon$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_emblem_get_icon$MH = RuntimeHelper.downcallHandle(
        "g_emblem_get_icon",
        constants$650.g_emblem_get_icon$FUNC, false
    );
    static final FunctionDescriptor g_emblem_get_origin$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_emblem_get_origin$MH = RuntimeHelper.downcallHandle(
        "g_emblem_get_origin",
        constants$650.g_emblem_get_origin$FUNC, false
    );
    static final FunctionDescriptor g_emblemed_icon_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_emblemed_icon_get_type$MH = RuntimeHelper.downcallHandle(
        "g_emblemed_icon_get_type",
        constants$650.g_emblemed_icon_get_type$FUNC, false
    );
    static final FunctionDescriptor g_emblemed_icon_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_emblemed_icon_new$MH = RuntimeHelper.downcallHandle(
        "g_emblemed_icon_new",
        constants$650.g_emblemed_icon_new$FUNC, false
    );
    static final FunctionDescriptor g_emblemed_icon_get_icon$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_emblemed_icon_get_icon$MH = RuntimeHelper.downcallHandle(
        "g_emblemed_icon_get_icon",
        constants$650.g_emblemed_icon_get_icon$FUNC, false
    );
    static final FunctionDescriptor g_emblemed_icon_get_emblems$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_emblemed_icon_get_emblems$MH = RuntimeHelper.downcallHandle(
        "g_emblemed_icon_get_emblems",
        constants$650.g_emblemed_icon_get_emblems$FUNC, false
    );
}


