// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1141 {

    static final FunctionDescriptor cairo_scaled_font_text_to_glyphs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_scaled_font_text_to_glyphs$MH = RuntimeHelper.downcallHandle(
        "cairo_scaled_font_text_to_glyphs",
        constants$1141.cairo_scaled_font_text_to_glyphs$FUNC, false
    );
    static final FunctionDescriptor cairo_scaled_font_get_font_face$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_scaled_font_get_font_face$MH = RuntimeHelper.downcallHandle(
        "cairo_scaled_font_get_font_face",
        constants$1141.cairo_scaled_font_get_font_face$FUNC, false
    );
    static final FunctionDescriptor cairo_scaled_font_get_font_matrix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_scaled_font_get_font_matrix$MH = RuntimeHelper.downcallHandle(
        "cairo_scaled_font_get_font_matrix",
        constants$1141.cairo_scaled_font_get_font_matrix$FUNC, false
    );
    static final FunctionDescriptor cairo_scaled_font_get_ctm$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_scaled_font_get_ctm$MH = RuntimeHelper.downcallHandle(
        "cairo_scaled_font_get_ctm",
        constants$1141.cairo_scaled_font_get_ctm$FUNC, false
    );
    static final FunctionDescriptor cairo_scaled_font_get_scale_matrix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_scaled_font_get_scale_matrix$MH = RuntimeHelper.downcallHandle(
        "cairo_scaled_font_get_scale_matrix",
        constants$1141.cairo_scaled_font_get_scale_matrix$FUNC, false
    );
    static final FunctionDescriptor cairo_scaled_font_get_font_options$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_scaled_font_get_font_options$MH = RuntimeHelper.downcallHandle(
        "cairo_scaled_font_get_font_options",
        constants$1141.cairo_scaled_font_get_font_options$FUNC, false
    );
}


