// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1452 {

    static final FunctionDescriptor gtk_window_get_focus_visible$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_focus_visible$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_focus_visible",
        constants$1452.gtk_window_get_focus_visible$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_resizable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_window_set_resizable$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_resizable",
        constants$1452.gtk_window_set_resizable$FUNC, false
    );
    static final FunctionDescriptor gtk_window_get_resizable$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_resizable$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_resizable",
        constants$1452.gtk_window_get_resizable$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_gravity$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_window_set_gravity$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_gravity",
        constants$1452.gtk_window_set_gravity$FUNC, false
    );
    static final FunctionDescriptor gtk_window_get_gravity$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_gravity$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_gravity",
        constants$1452.gtk_window_get_gravity$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_geometry_hints$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_window_set_geometry_hints$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_geometry_hints",
        constants$1452.gtk_window_set_geometry_hints$FUNC, false
    );
}


