// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2246 {

    static final FunctionDescriptor glib_autoptr_clear_GtkSearchEntry$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkSearchEntry$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkSearchEntry",
        constants$2246.glib_autoptr_clear_GtkSearchEntry$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkSearchEntry$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkSearchEntry$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkSearchEntry",
        constants$2246.glib_autoptr_cleanup_GtkSearchEntry$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkSearchEntry$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkSearchEntry$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkSearchEntry",
        constants$2246.glib_listautoptr_cleanup_GtkSearchEntry$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkSearchEntry$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkSearchEntry$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkSearchEntry",
        constants$2246.glib_slistautoptr_cleanup_GtkSearchEntry$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkSearchEntry$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkSearchEntry$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkSearchEntry",
        constants$2246.glib_queueautoptr_cleanup_GtkSearchEntry$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkSeparator$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkSeparator$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkSeparator",
        constants$2246.glib_autoptr_clear_GtkSeparator$FUNC, false
    );
}


