// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1488 {

    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkMenu$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkMenu$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkMenu",
        constants$1488.glib_queueautoptr_cleanup_GtkMenu$FUNC, false
    );
    static final FunctionDescriptor gtk_label_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_label_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_label_get_type",
        constants$1488.gtk_label_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_label_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_label_new$MH = RuntimeHelper.downcallHandle(
        "gtk_label_new",
        constants$1488.gtk_label_new$FUNC, false
    );
    static final FunctionDescriptor gtk_label_new_with_mnemonic$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_label_new_with_mnemonic$MH = RuntimeHelper.downcallHandle(
        "gtk_label_new_with_mnemonic",
        constants$1488.gtk_label_new_with_mnemonic$FUNC, false
    );
    static final FunctionDescriptor gtk_label_set_text$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_label_set_text$MH = RuntimeHelper.downcallHandle(
        "gtk_label_set_text",
        constants$1488.gtk_label_set_text$FUNC, false
    );
    static final FunctionDescriptor gtk_label_get_text$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_label_get_text$MH = RuntimeHelper.downcallHandle(
        "gtk_label_get_text",
        constants$1488.gtk_label_get_text$FUNC, false
    );
}


