// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1409 {

    static final FunctionDescriptor gtk_widget_set_size_request$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_size_request$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_size_request",
        constants$1409.gtk_widget_set_size_request$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_get_size_request$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_size_request$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_size_request",
        constants$1409.gtk_widget_get_size_request$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_set_events$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_events$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_events",
        constants$1409.gtk_widget_set_events$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_add_events$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_add_events$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_add_events",
        constants$1409.gtk_widget_add_events$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_set_device_events$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_device_events$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_device_events",
        constants$1409.gtk_widget_set_device_events$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_add_device_events$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_add_device_events$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_add_device_events",
        constants$1409.gtk_widget_add_device_events$FUNC, false
    );
}


