// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1546 {

    static final FunctionDescriptor gtk_tree_view_column_get_sizing$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_column_get_sizing$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_column_get_sizing",
        constants$1546.gtk_tree_view_column_get_sizing$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_view_column_get_x_offset$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_column_get_x_offset$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_column_get_x_offset",
        constants$1546.gtk_tree_view_column_get_x_offset$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_view_column_get_width$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_column_get_width$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_column_get_width",
        constants$1546.gtk_tree_view_column_get_width$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_view_column_get_fixed_width$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tree_view_column_get_fixed_width$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_column_get_fixed_width",
        constants$1546.gtk_tree_view_column_get_fixed_width$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_view_column_set_fixed_width$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tree_view_column_set_fixed_width$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_column_set_fixed_width",
        constants$1546.gtk_tree_view_column_set_fixed_width$FUNC, false
    );
    static final FunctionDescriptor gtk_tree_view_column_set_min_width$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tree_view_column_set_min_width$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_column_set_min_width",
        constants$1546.gtk_tree_view_column_set_min_width$FUNC, false
    );
}


