// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1224 {

    static final FunctionDescriptor gdk_window_begin_resize_drag$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_window_begin_resize_drag$MH = RuntimeHelper.downcallHandle(
        "gdk_window_begin_resize_drag",
        constants$1224.gdk_window_begin_resize_drag$FUNC, false
    );
    static final FunctionDescriptor gdk_window_begin_resize_drag_for_device$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_window_begin_resize_drag_for_device$MH = RuntimeHelper.downcallHandle(
        "gdk_window_begin_resize_drag_for_device",
        constants$1224.gdk_window_begin_resize_drag_for_device$FUNC, false
    );
    static final FunctionDescriptor gdk_window_begin_move_drag$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_window_begin_move_drag$MH = RuntimeHelper.downcallHandle(
        "gdk_window_begin_move_drag",
        constants$1224.gdk_window_begin_move_drag$FUNC, false
    );
    static final FunctionDescriptor gdk_window_begin_move_drag_for_device$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_window_begin_move_drag_for_device$MH = RuntimeHelper.downcallHandle(
        "gdk_window_begin_move_drag_for_device",
        constants$1224.gdk_window_begin_move_drag_for_device$FUNC, false
    );
    static final FunctionDescriptor gdk_window_invalidate_rect$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_window_invalidate_rect$MH = RuntimeHelper.downcallHandle(
        "gdk_window_invalidate_rect",
        constants$1224.gdk_window_invalidate_rect$FUNC, false
    );
    static final FunctionDescriptor gdk_window_invalidate_region$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_window_invalidate_region$MH = RuntimeHelper.downcallHandle(
        "gdk_window_invalidate_region",
        constants$1224.gdk_window_invalidate_region$FUNC, false
    );
}


