// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2088 {

    static final FunctionDescriptor gtk_color_selection_palette_to_string$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_color_selection_palette_to_string$MH = RuntimeHelper.downcallHandle(
        "gtk_color_selection_palette_to_string",
        constants$2088.gtk_color_selection_palette_to_string$FUNC, false
    );
    static final FunctionDescriptor gtk_color_selection_set_change_palette_with_screen_hook$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_color_selection_set_change_palette_with_screen_hook$MH = RuntimeHelper.downcallHandle(
        "gtk_color_selection_set_change_palette_with_screen_hook",
        constants$2088.gtk_color_selection_set_change_palette_with_screen_hook$FUNC, false
    );
    static final FunctionDescriptor gtk_color_selection_set_current_color$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_color_selection_set_current_color$MH = RuntimeHelper.downcallHandle(
        "gtk_color_selection_set_current_color",
        constants$2088.gtk_color_selection_set_current_color$FUNC, false
    );
    static final FunctionDescriptor gtk_color_selection_get_current_color$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_color_selection_get_current_color$MH = RuntimeHelper.downcallHandle(
        "gtk_color_selection_get_current_color",
        constants$2088.gtk_color_selection_get_current_color$FUNC, false
    );
    static final FunctionDescriptor gtk_color_selection_set_previous_color$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_color_selection_set_previous_color$MH = RuntimeHelper.downcallHandle(
        "gtk_color_selection_set_previous_color",
        constants$2088.gtk_color_selection_set_previous_color$FUNC, false
    );
    static final FunctionDescriptor gtk_color_selection_get_previous_color$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_color_selection_get_previous_color$MH = RuntimeHelper.downcallHandle(
        "gtk_color_selection_get_previous_color",
        constants$2088.gtk_color_selection_get_previous_color$FUNC, false
    );
}


