// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1721 {

    static final FunctionDescriptor gtk_expander_set_label_fill$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_expander_set_label_fill$MH = RuntimeHelper.downcallHandle(
        "gtk_expander_set_label_fill",
        constants$1721.gtk_expander_set_label_fill$FUNC, false
    );
    static final FunctionDescriptor gtk_expander_get_label_fill$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_expander_get_label_fill$MH = RuntimeHelper.downcallHandle(
        "gtk_expander_get_label_fill",
        constants$1721.gtk_expander_get_label_fill$FUNC, false
    );
    static final FunctionDescriptor gtk_expander_set_resize_toplevel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_expander_set_resize_toplevel$MH = RuntimeHelper.downcallHandle(
        "gtk_expander_set_resize_toplevel",
        constants$1721.gtk_expander_set_resize_toplevel$FUNC, false
    );
    static final FunctionDescriptor gtk_expander_get_resize_toplevel$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_expander_get_resize_toplevel$MH = RuntimeHelper.downcallHandle(
        "gtk_expander_get_resize_toplevel",
        constants$1721.gtk_expander_get_resize_toplevel$FUNC, false
    );
    static final FunctionDescriptor gtk_fixed_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_fixed_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_fixed_get_type",
        constants$1721.gtk_fixed_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_fixed_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_fixed_new$MH = RuntimeHelper.downcallHandle(
        "gtk_fixed_new",
        constants$1721.gtk_fixed_new$FUNC, false
    );
}


