// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1430 {

    static final FunctionDescriptor gtk_widget_get_font_map$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_font_map$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_font_map",
        constants$1430.gtk_widget_get_font_map$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkWidget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkWidget$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkWidget",
        constants$1430.glib_autoptr_clear_GtkWidget$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkWidget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkWidget$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkWidget",
        constants$1430.glib_autoptr_cleanup_GtkWidget$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkWidget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkWidget$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkWidget",
        constants$1430.glib_listautoptr_cleanup_GtkWidget$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkWidget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkWidget$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkWidget",
        constants$1430.glib_slistautoptr_cleanup_GtkWidget$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkWidget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkWidget$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkWidget",
        constants$1430.glib_queueautoptr_cleanup_GtkWidget$FUNC, false
    );
}


