// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1412 {

    static final FunctionDescriptor gtk_widget_get_root_window$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_root_window$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_root_window",
        constants$1412.gtk_widget_get_root_window$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_get_settings$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_settings$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_settings",
        constants$1412.gtk_widget_get_settings$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_get_clipboard$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_clipboard$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_clipboard",
        constants$1412.gtk_widget_get_clipboard$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_get_hexpand$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_hexpand$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_hexpand",
        constants$1412.gtk_widget_get_hexpand$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_set_hexpand$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_set_hexpand$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_set_hexpand",
        constants$1412.gtk_widget_set_hexpand$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_get_hexpand_set$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_get_hexpand_set$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_get_hexpand_set",
        constants$1412.gtk_widget_get_hexpand_set$FUNC, false
    );
}


