// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1777 {

    static final FunctionDescriptor gtk_header_bar_set_custom_title$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_header_bar_set_custom_title$MH = RuntimeHelper.downcallHandle(
        "gtk_header_bar_set_custom_title",
        constants$1777.gtk_header_bar_set_custom_title$FUNC, false
    );
    static final FunctionDescriptor gtk_header_bar_get_custom_title$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_header_bar_get_custom_title$MH = RuntimeHelper.downcallHandle(
        "gtk_header_bar_get_custom_title",
        constants$1777.gtk_header_bar_get_custom_title$FUNC, false
    );
    static final FunctionDescriptor gtk_header_bar_pack_start$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_header_bar_pack_start$MH = RuntimeHelper.downcallHandle(
        "gtk_header_bar_pack_start",
        constants$1777.gtk_header_bar_pack_start$FUNC, false
    );
    static final FunctionDescriptor gtk_header_bar_pack_end$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_header_bar_pack_end$MH = RuntimeHelper.downcallHandle(
        "gtk_header_bar_pack_end",
        constants$1777.gtk_header_bar_pack_end$FUNC, false
    );
    static final FunctionDescriptor gtk_header_bar_get_show_close_button$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_header_bar_get_show_close_button$MH = RuntimeHelper.downcallHandle(
        "gtk_header_bar_get_show_close_button",
        constants$1777.gtk_header_bar_get_show_close_button$FUNC, false
    );
    static final FunctionDescriptor gtk_header_bar_set_show_close_button$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_header_bar_set_show_close_button$MH = RuntimeHelper.downcallHandle(
        "gtk_header_bar_set_show_close_button",
        constants$1777.gtk_header_bar_set_show_close_button$FUNC, false
    );
}


