// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1081 {

    static final FunctionDescriptor pango_tab_array_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_tab_array_copy$MH = RuntimeHelper.downcallHandle(
        "pango_tab_array_copy",
        constants$1081.pango_tab_array_copy$FUNC, false
    );
    static final FunctionDescriptor pango_tab_array_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_tab_array_free$MH = RuntimeHelper.downcallHandle(
        "pango_tab_array_free",
        constants$1081.pango_tab_array_free$FUNC, false
    );
    static final FunctionDescriptor pango_tab_array_get_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_tab_array_get_size$MH = RuntimeHelper.downcallHandle(
        "pango_tab_array_get_size",
        constants$1081.pango_tab_array_get_size$FUNC, false
    );
    static final FunctionDescriptor pango_tab_array_resize$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pango_tab_array_resize$MH = RuntimeHelper.downcallHandle(
        "pango_tab_array_resize",
        constants$1081.pango_tab_array_resize$FUNC, false
    );
    static final FunctionDescriptor pango_tab_array_set_tab$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pango_tab_array_set_tab$MH = RuntimeHelper.downcallHandle(
        "pango_tab_array_set_tab",
        constants$1081.pango_tab_array_set_tab$FUNC, false
    );
    static final FunctionDescriptor pango_tab_array_get_tab$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_tab_array_get_tab$MH = RuntimeHelper.downcallHandle(
        "pango_tab_array_get_tab",
        constants$1081.pango_tab_array_get_tab$FUNC, false
    );
}


