// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$819 {

    static final FunctionDescriptor g_socket_listener_accept_socket_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_listener_accept_socket_finish$MH = RuntimeHelper.downcallHandle(
        "g_socket_listener_accept_socket_finish",
        constants$819.g_socket_listener_accept_socket_finish$FUNC, false
    );
    static final FunctionDescriptor g_socket_listener_accept$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_listener_accept$MH = RuntimeHelper.downcallHandle(
        "g_socket_listener_accept",
        constants$819.g_socket_listener_accept$FUNC, false
    );
    static final FunctionDescriptor g_socket_listener_accept_async$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_listener_accept_async$MH = RuntimeHelper.downcallHandle(
        "g_socket_listener_accept_async",
        constants$819.g_socket_listener_accept_async$FUNC, false
    );
    static final FunctionDescriptor g_socket_listener_accept_finish$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_listener_accept_finish$MH = RuntimeHelper.downcallHandle(
        "g_socket_listener_accept_finish",
        constants$819.g_socket_listener_accept_finish$FUNC, false
    );
    static final FunctionDescriptor g_socket_listener_close$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_socket_listener_close$MH = RuntimeHelper.downcallHandle(
        "g_socket_listener_close",
        constants$819.g_socket_listener_close$FUNC, false
    );
    static final FunctionDescriptor g_socket_service_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle g_socket_service_get_type$MH = RuntimeHelper.downcallHandle(
        "g_socket_service_get_type",
        constants$819.g_socket_service_get_type$FUNC, false
    );
}


