// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1484 {

    static final FunctionDescriptor gtk_menu_set_accel_group$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_menu_set_accel_group$MH = RuntimeHelper.downcallHandle(
        "gtk_menu_set_accel_group",
        constants$1484.gtk_menu_set_accel_group$FUNC, false
    );
    static final FunctionDescriptor gtk_menu_get_accel_group$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_menu_get_accel_group$MH = RuntimeHelper.downcallHandle(
        "gtk_menu_get_accel_group",
        constants$1484.gtk_menu_get_accel_group$FUNC, false
    );
    static final FunctionDescriptor gtk_menu_set_accel_path$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_menu_set_accel_path$MH = RuntimeHelper.downcallHandle(
        "gtk_menu_set_accel_path",
        constants$1484.gtk_menu_set_accel_path$FUNC, false
    );
    static final FunctionDescriptor gtk_menu_get_accel_path$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_menu_get_accel_path$MH = RuntimeHelper.downcallHandle(
        "gtk_menu_get_accel_path",
        constants$1484.gtk_menu_get_accel_path$FUNC, false
    );
    static final FunctionDescriptor gtk_menu_attach_to_widget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_menu_attach_to_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_menu_attach_to_widget",
        constants$1484.gtk_menu_attach_to_widget$FUNC, false
    );
    static final FunctionDescriptor gtk_menu_detach$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_menu_detach$MH = RuntimeHelper.downcallHandle(
        "gtk_menu_detach",
        constants$1484.gtk_menu_detach$FUNC, false
    );
}


