// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1449 {

    static final FunctionDescriptor gtk_window_get_type_hint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_type_hint$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_type_hint",
        constants$1449.gtk_window_get_type_hint$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_skip_taskbar_hint$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_window_set_skip_taskbar_hint$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_skip_taskbar_hint",
        constants$1449.gtk_window_set_skip_taskbar_hint$FUNC, false
    );
    static final FunctionDescriptor gtk_window_get_skip_taskbar_hint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_skip_taskbar_hint$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_skip_taskbar_hint",
        constants$1449.gtk_window_get_skip_taskbar_hint$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_skip_pager_hint$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_window_set_skip_pager_hint$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_skip_pager_hint",
        constants$1449.gtk_window_set_skip_pager_hint$FUNC, false
    );
    static final FunctionDescriptor gtk_window_get_skip_pager_hint$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_skip_pager_hint$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_skip_pager_hint",
        constants$1449.gtk_window_get_skip_pager_hint$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_urgency_hint$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_window_set_urgency_hint$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_urgency_hint",
        constants$1449.gtk_window_set_urgency_hint$FUNC, false
    );
}


