// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1213 {

    static final FunctionDescriptor gdk_window_set_title$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_set_title$MH = RuntimeHelper.downcallHandle(
        "gdk_window_set_title",
        constants$1213.gdk_window_set_title$FUNC, false
    );
    static final FunctionDescriptor gdk_window_set_role$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_set_role$MH = RuntimeHelper.downcallHandle(
        "gdk_window_set_role",
        constants$1213.gdk_window_set_role$FUNC, false
    );
    static final FunctionDescriptor gdk_window_set_startup_id$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_set_startup_id$MH = RuntimeHelper.downcallHandle(
        "gdk_window_set_startup_id",
        constants$1213.gdk_window_set_startup_id$FUNC, false
    );
    static final FunctionDescriptor gdk_window_set_transient_for$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_set_transient_for$MH = RuntimeHelper.downcallHandle(
        "gdk_window_set_transient_for",
        constants$1213.gdk_window_set_transient_for$FUNC, false
    );
    static final FunctionDescriptor gdk_window_set_background$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_set_background$MH = RuntimeHelper.downcallHandle(
        "gdk_window_set_background",
        constants$1213.gdk_window_set_background$FUNC, false
    );
    static final FunctionDescriptor gdk_window_set_background_rgba$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_set_background_rgba$MH = RuntimeHelper.downcallHandle(
        "gdk_window_set_background_rgba",
        constants$1213.gdk_window_set_background_rgba$FUNC, false
    );
}


