// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1065 {

    static final FunctionDescriptor pango_fontset_foreach$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_fontset_foreach$MH = RuntimeHelper.downcallHandle(
        "pango_fontset_foreach",
        constants$1065.pango_fontset_foreach$FUNC, false
    );
    static final FunctionDescriptor pango_font_map_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle pango_font_map_get_type$MH = RuntimeHelper.downcallHandle(
        "pango_font_map_get_type",
        constants$1065.pango_font_map_get_type$FUNC, false
    );
    static final FunctionDescriptor pango_font_map_create_context$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_font_map_create_context$MH = RuntimeHelper.downcallHandle(
        "pango_font_map_create_context",
        constants$1065.pango_font_map_create_context$FUNC, false
    );
    static final FunctionDescriptor pango_font_map_load_font$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_font_map_load_font$MH = RuntimeHelper.downcallHandle(
        "pango_font_map_load_font",
        constants$1065.pango_font_map_load_font$FUNC, false
    );
    static final FunctionDescriptor pango_font_map_load_fontset$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_font_map_load_fontset$MH = RuntimeHelper.downcallHandle(
        "pango_font_map_load_fontset",
        constants$1065.pango_font_map_load_fontset$FUNC, false
    );
    static final FunctionDescriptor pango_font_map_list_families$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_font_map_list_families$MH = RuntimeHelper.downcallHandle(
        "pango_font_map_list_families",
        constants$1065.pango_font_map_list_families$FUNC, false
    );
}


