// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$197 {

    static final FunctionDescriptor g_io_channel_unix_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_io_channel_unix_new$MH = RuntimeHelper.downcallHandle(
        "g_io_channel_unix_new",
        constants$197.g_io_channel_unix_new$FUNC, false
    );
    static final FunctionDescriptor g_io_channel_unix_get_fd$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_io_channel_unix_get_fd$MH = RuntimeHelper.downcallHandle(
        "g_io_channel_unix_get_fd",
        constants$197.g_io_channel_unix_get_fd$FUNC, false
    );
    static final  GroupLayout g_io_watch_funcs$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("prepare"),
        Constants$root.C_POINTER$LAYOUT.withName("check"),
        Constants$root.C_POINTER$LAYOUT.withName("dispatch"),
        Constants$root.C_POINTER$LAYOUT.withName("finalize"),
        Constants$root.C_POINTER$LAYOUT.withName("closure_callback"),
        Constants$root.C_POINTER$LAYOUT.withName("closure_marshal")
    ).withName("_GSourceFuncs");
    static final MemorySegment g_io_watch_funcs$SEGMENT = RuntimeHelper.lookupGlobalVariable("g_io_watch_funcs", constants$197.g_io_watch_funcs$LAYOUT);
    static final FunctionDescriptor g_key_file_error_quark$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle g_key_file_error_quark$MH = RuntimeHelper.downcallHandle(
        "g_key_file_error_quark",
        constants$197.g_key_file_error_quark$FUNC, false
    );
    static final FunctionDescriptor g_key_file_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle g_key_file_new$MH = RuntimeHelper.downcallHandle(
        "g_key_file_new",
        constants$197.g_key_file_new$FUNC, false
    );
    static final FunctionDescriptor g_key_file_ref$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_key_file_ref$MH = RuntimeHelper.downcallHandle(
        "g_key_file_ref",
        constants$197.g_key_file_ref$FUNC, false
    );
}


