// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2064 {

    static final FunctionDescriptor gtk_widget_path_iter_has_name$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_path_iter_has_name$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_path_iter_has_name",
        constants$2064.gtk_widget_path_iter_has_name$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_path_iter_has_qname$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_path_iter_has_qname$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_path_iter_has_qname",
        constants$2064.gtk_widget_path_iter_has_qname$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_path_iter_get_state$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_path_iter_get_state$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_path_iter_get_state",
        constants$2064.gtk_widget_path_iter_get_state$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_path_iter_set_state$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_widget_path_iter_set_state$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_path_iter_set_state",
        constants$2064.gtk_widget_path_iter_set_state$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_path_iter_add_class$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_path_iter_add_class$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_path_iter_add_class",
        constants$2064.gtk_widget_path_iter_add_class$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_path_iter_remove_class$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_widget_path_iter_remove_class$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_path_iter_remove_class",
        constants$2064.gtk_widget_path_iter_remove_class$FUNC, false
    );
}


