// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1207 {

    static final FunctionDescriptor gdk_window_set_child_shapes$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_set_child_shapes$MH = RuntimeHelper.downcallHandle(
        "gdk_window_set_child_shapes",
        constants$1207.gdk_window_set_child_shapes$FUNC, false
    );
    static final FunctionDescriptor gdk_window_get_composited$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_get_composited$MH = RuntimeHelper.downcallHandle(
        "gdk_window_get_composited",
        constants$1207.gdk_window_get_composited$FUNC, false
    );
    static final FunctionDescriptor gdk_window_set_composited$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_window_set_composited$MH = RuntimeHelper.downcallHandle(
        "gdk_window_set_composited",
        constants$1207.gdk_window_set_composited$FUNC, false
    );
    static final FunctionDescriptor gdk_window_merge_child_shapes$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_merge_child_shapes$MH = RuntimeHelper.downcallHandle(
        "gdk_window_merge_child_shapes",
        constants$1207.gdk_window_merge_child_shapes$FUNC, false
    );
    static final FunctionDescriptor gdk_window_input_shape_combine_region$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_window_input_shape_combine_region$MH = RuntimeHelper.downcallHandle(
        "gdk_window_input_shape_combine_region",
        constants$1207.gdk_window_input_shape_combine_region$FUNC, false
    );
    static final FunctionDescriptor gdk_window_set_child_input_shapes$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_window_set_child_input_shapes$MH = RuntimeHelper.downcallHandle(
        "gdk_window_set_child_input_shapes",
        constants$1207.gdk_window_set_child_input_shapes$FUNC, false
    );
}


