// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1813 {

    static final FunctionDescriptor gtk_icon_view_get_columns$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_view_get_columns$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_get_columns",
        constants$1813.gtk_icon_view_get_columns$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_view_set_item_width$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_icon_view_set_item_width$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_set_item_width",
        constants$1813.gtk_icon_view_set_item_width$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_view_get_item_width$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_view_get_item_width$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_get_item_width",
        constants$1813.gtk_icon_view_get_item_width$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_view_set_spacing$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_icon_view_set_spacing$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_set_spacing",
        constants$1813.gtk_icon_view_set_spacing$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_view_get_spacing$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_view_get_spacing$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_get_spacing",
        constants$1813.gtk_icon_view_get_spacing$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_view_set_row_spacing$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_icon_view_set_row_spacing$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_view_set_row_spacing",
        constants$1813.gtk_icon_view_set_row_spacing$FUNC, false
    );
}


