// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$766 {

    static final FunctionDescriptor g_proxy_address_get_destination_protocol$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_proxy_address_get_destination_protocol$MH = RuntimeHelper.downcallHandle(
        "g_proxy_address_get_destination_protocol",
        constants$766.g_proxy_address_get_destination_protocol$FUNC, false
    );
    static final FunctionDescriptor g_proxy_address_get_destination_hostname$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_proxy_address_get_destination_hostname$MH = RuntimeHelper.downcallHandle(
        "g_proxy_address_get_destination_hostname",
        constants$766.g_proxy_address_get_destination_hostname$FUNC, false
    );
    static final FunctionDescriptor g_proxy_address_get_destination_port$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_proxy_address_get_destination_port$MH = RuntimeHelper.downcallHandle(
        "g_proxy_address_get_destination_port",
        constants$766.g_proxy_address_get_destination_port$FUNC, false
    );
    static final FunctionDescriptor g_proxy_address_get_username$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_proxy_address_get_username$MH = RuntimeHelper.downcallHandle(
        "g_proxy_address_get_username",
        constants$766.g_proxy_address_get_username$FUNC, false
    );
    static final FunctionDescriptor g_proxy_address_get_password$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_proxy_address_get_password$MH = RuntimeHelper.downcallHandle(
        "g_proxy_address_get_password",
        constants$766.g_proxy_address_get_password$FUNC, false
    );
    static final FunctionDescriptor g_proxy_address_get_uri$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_proxy_address_get_uri$MH = RuntimeHelper.downcallHandle(
        "g_proxy_address_get_uri",
        constants$766.g_proxy_address_get_uri$FUNC, false
    );
}


