// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2105 {

    static final FunctionDescriptor gtk_numerable_icon_set_background_gicon$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_numerable_icon_set_background_gicon$MH = RuntimeHelper.downcallHandle(
        "gtk_numerable_icon_set_background_gicon",
        constants$2105.gtk_numerable_icon_set_background_gicon$FUNC, false
    );
    static final FunctionDescriptor gtk_numerable_icon_get_background_gicon$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_numerable_icon_get_background_gicon$MH = RuntimeHelper.downcallHandle(
        "gtk_numerable_icon_get_background_gicon",
        constants$2105.gtk_numerable_icon_get_background_gicon$FUNC, false
    );
    static final FunctionDescriptor gtk_numerable_icon_set_background_icon_name$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_numerable_icon_set_background_icon_name$MH = RuntimeHelper.downcallHandle(
        "gtk_numerable_icon_set_background_icon_name",
        constants$2105.gtk_numerable_icon_set_background_icon_name$FUNC, false
    );
    static final FunctionDescriptor gtk_numerable_icon_get_background_icon_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_numerable_icon_get_background_icon_name$MH = RuntimeHelper.downcallHandle(
        "gtk_numerable_icon_get_background_icon_name",
        constants$2105.gtk_numerable_icon_get_background_icon_name$FUNC, false
    );
    static final FunctionDescriptor gtk_toggle_action_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_toggle_action_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_toggle_action_get_type",
        constants$2105.gtk_toggle_action_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_toggle_action_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_toggle_action_new$MH = RuntimeHelper.downcallHandle(
        "gtk_toggle_action_new",
        constants$2105.gtk_toggle_action_new$FUNC, false
    );
}


