// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$139 {

    static final FunctionDescriptor g_hash_table_iter_next$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_hash_table_iter_next$MH = RuntimeHelper.downcallHandle(
        "g_hash_table_iter_next",
        constants$139.g_hash_table_iter_next$FUNC, false
    );
    static final FunctionDescriptor g_hash_table_iter_get_hash_table$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_hash_table_iter_get_hash_table$MH = RuntimeHelper.downcallHandle(
        "g_hash_table_iter_get_hash_table",
        constants$139.g_hash_table_iter_get_hash_table$FUNC, false
    );
    static final FunctionDescriptor g_hash_table_iter_remove$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_hash_table_iter_remove$MH = RuntimeHelper.downcallHandle(
        "g_hash_table_iter_remove",
        constants$139.g_hash_table_iter_remove$FUNC, false
    );
    static final FunctionDescriptor g_hash_table_iter_replace$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_hash_table_iter_replace$MH = RuntimeHelper.downcallHandle(
        "g_hash_table_iter_replace",
        constants$139.g_hash_table_iter_replace$FUNC, false
    );
    static final FunctionDescriptor g_hash_table_iter_steal$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_hash_table_iter_steal$MH = RuntimeHelper.downcallHandle(
        "g_hash_table_iter_steal",
        constants$139.g_hash_table_iter_steal$FUNC, false
    );
    static final FunctionDescriptor g_hash_table_ref$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_hash_table_ref$MH = RuntimeHelper.downcallHandle(
        "g_hash_table_ref",
        constants$139.g_hash_table_ref$FUNC, false
    );
}


