// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$357 {

    static final FunctionDescriptor pthread_mutexattr_setprotocol$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pthread_mutexattr_setprotocol$MH = RuntimeHelper.downcallHandle(
        "pthread_mutexattr_setprotocol",
        constants$357.pthread_mutexattr_setprotocol$FUNC, false
    );
    static final FunctionDescriptor pthread_mutexattr_getprioceiling$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_mutexattr_getprioceiling$MH = RuntimeHelper.downcallHandle(
        "pthread_mutexattr_getprioceiling",
        constants$357.pthread_mutexattr_getprioceiling$FUNC, false
    );
    static final FunctionDescriptor pthread_mutexattr_setprioceiling$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pthread_mutexattr_setprioceiling$MH = RuntimeHelper.downcallHandle(
        "pthread_mutexattr_setprioceiling",
        constants$357.pthread_mutexattr_setprioceiling$FUNC, false
    );
    static final FunctionDescriptor pthread_mutexattr_getrobust$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_mutexattr_getrobust$MH = RuntimeHelper.downcallHandle(
        "pthread_mutexattr_getrobust",
        constants$357.pthread_mutexattr_getrobust$FUNC, false
    );
    static final FunctionDescriptor pthread_mutexattr_setrobust$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pthread_mutexattr_setrobust$MH = RuntimeHelper.downcallHandle(
        "pthread_mutexattr_setrobust",
        constants$357.pthread_mutexattr_setrobust$FUNC, false
    );
    static final FunctionDescriptor pthread_rwlock_init$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pthread_rwlock_init$MH = RuntimeHelper.downcallHandle(
        "pthread_rwlock_init",
        constants$357.pthread_rwlock_init$FUNC, false
    );
}


