// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1451 {

    static final FunctionDescriptor gtk_window_get_destroy_with_parent$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_destroy_with_parent$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_destroy_with_parent",
        constants$1451.gtk_window_get_destroy_with_parent$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_hide_titlebar_when_maximized$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_window_set_hide_titlebar_when_maximized$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_hide_titlebar_when_maximized",
        constants$1451.gtk_window_set_hide_titlebar_when_maximized$FUNC, false
    );
    static final FunctionDescriptor gtk_window_get_hide_titlebar_when_maximized$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_hide_titlebar_when_maximized$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_hide_titlebar_when_maximized",
        constants$1451.gtk_window_get_hide_titlebar_when_maximized$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_mnemonics_visible$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_window_set_mnemonics_visible$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_mnemonics_visible",
        constants$1451.gtk_window_set_mnemonics_visible$FUNC, false
    );
    static final FunctionDescriptor gtk_window_get_mnemonics_visible$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_window_get_mnemonics_visible$MH = RuntimeHelper.downcallHandle(
        "gtk_window_get_mnemonics_visible",
        constants$1451.gtk_window_get_mnemonics_visible$FUNC, false
    );
    static final FunctionDescriptor gtk_window_set_focus_visible$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_window_set_focus_visible$MH = RuntimeHelper.downcallHandle(
        "gtk_window_set_focus_visible",
        constants$1451.gtk_window_set_focus_visible$FUNC, false
    );
}


