// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2289 {

    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkTreePath$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkTreePath$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkTreePath",
        constants$2289.glib_slistautoptr_cleanup_GtkTreePath$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkTreePath$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkTreePath$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkTreePath",
        constants$2289.glib_queueautoptr_cleanup_GtkTreePath$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkTreeRowReference$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkTreeRowReference$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkTreeRowReference",
        constants$2289.glib_autoptr_clear_GtkTreeRowReference$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkTreeRowReference$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkTreeRowReference$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkTreeRowReference",
        constants$2289.glib_autoptr_cleanup_GtkTreeRowReference$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkTreeRowReference$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkTreeRowReference$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkTreeRowReference",
        constants$2289.glib_listautoptr_cleanup_GtkTreeRowReference$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkTreeRowReference$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkTreeRowReference$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkTreeRowReference",
        constants$2289.glib_slistautoptr_cleanup_GtkTreeRowReference$FUNC, false
    );
}


