// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2153 {

    static final FunctionDescriptor glib_listautoptr_cleanup_GtkButton$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkButton$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkButton",
        constants$2153.glib_listautoptr_cleanup_GtkButton$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkButton$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkButton$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkButton",
        constants$2153.glib_slistautoptr_cleanup_GtkButton$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkButton$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkButton$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkButton",
        constants$2153.glib_queueautoptr_cleanup_GtkButton$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkButtonBox$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkButtonBox$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkButtonBox",
        constants$2153.glib_autoptr_clear_GtkButtonBox$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkButtonBox$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkButtonBox$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkButtonBox",
        constants$2153.glib_autoptr_cleanup_GtkButtonBox$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkButtonBox$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkButtonBox$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkButtonBox",
        constants$2153.glib_listautoptr_cleanup_GtkButtonBox$FUNC, false
    );
}


