// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1859 {

    static final FunctionDescriptor gtk_tool_item_set_tooltip_markup$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tool_item_set_tooltip_markup$MH = RuntimeHelper.downcallHandle(
        "gtk_tool_item_set_tooltip_markup",
        constants$1859.gtk_tool_item_set_tooltip_markup$FUNC, false
    );
    static final FunctionDescriptor gtk_tool_item_set_use_drag_window$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tool_item_set_use_drag_window$MH = RuntimeHelper.downcallHandle(
        "gtk_tool_item_set_use_drag_window",
        constants$1859.gtk_tool_item_set_use_drag_window$FUNC, false
    );
    static final FunctionDescriptor gtk_tool_item_get_use_drag_window$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tool_item_get_use_drag_window$MH = RuntimeHelper.downcallHandle(
        "gtk_tool_item_get_use_drag_window",
        constants$1859.gtk_tool_item_get_use_drag_window$FUNC, false
    );
    static final FunctionDescriptor gtk_tool_item_set_visible_horizontal$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tool_item_set_visible_horizontal$MH = RuntimeHelper.downcallHandle(
        "gtk_tool_item_set_visible_horizontal",
        constants$1859.gtk_tool_item_set_visible_horizontal$FUNC, false
    );
    static final FunctionDescriptor gtk_tool_item_get_visible_horizontal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_tool_item_get_visible_horizontal$MH = RuntimeHelper.downcallHandle(
        "gtk_tool_item_get_visible_horizontal",
        constants$1859.gtk_tool_item_get_visible_horizontal$FUNC, false
    );
    static final FunctionDescriptor gtk_tool_item_set_visible_vertical$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_tool_item_set_visible_vertical$MH = RuntimeHelper.downcallHandle(
        "gtk_tool_item_set_visible_vertical",
        constants$1859.gtk_tool_item_set_visible_vertical$FUNC, false
    );
}


