// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1882 {

    static final FunctionDescriptor gtk_paper_size_is_equal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_paper_size_is_equal$MH = RuntimeHelper.downcallHandle(
        "gtk_paper_size_is_equal",
        constants$1882.gtk_paper_size_is_equal$FUNC, false
    );
    static final FunctionDescriptor gtk_paper_size_get_paper_sizes$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_paper_size_get_paper_sizes$MH = RuntimeHelper.downcallHandle(
        "gtk_paper_size_get_paper_sizes",
        constants$1882.gtk_paper_size_get_paper_sizes$FUNC, false
    );
    static final FunctionDescriptor gtk_paper_size_get_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_paper_size_get_name$MH = RuntimeHelper.downcallHandle(
        "gtk_paper_size_get_name",
        constants$1882.gtk_paper_size_get_name$FUNC, false
    );
    static final FunctionDescriptor gtk_paper_size_get_display_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_paper_size_get_display_name$MH = RuntimeHelper.downcallHandle(
        "gtk_paper_size_get_display_name",
        constants$1882.gtk_paper_size_get_display_name$FUNC, false
    );
    static final FunctionDescriptor gtk_paper_size_get_ppd_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_paper_size_get_ppd_name$MH = RuntimeHelper.downcallHandle(
        "gtk_paper_size_get_ppd_name",
        constants$1882.gtk_paper_size_get_ppd_name$FUNC, false
    );
    static final FunctionDescriptor gtk_paper_size_get_width$FUNC = FunctionDescriptor.of(Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_paper_size_get_width$MH = RuntimeHelper.downcallHandle(
        "gtk_paper_size_get_width",
        constants$1882.gtk_paper_size_get_width$FUNC, false
    );
}


