// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1657 {

    static final FunctionDescriptor gtk_binding_entry_skip$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_binding_entry_skip$MH = RuntimeHelper.downcallHandle(
        "gtk_binding_entry_skip",
        constants$1657.gtk_binding_entry_skip$FUNC, false
    );
    static final FunctionDescriptor gtk_binding_entry_add_signal$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_binding_entry_add_signal$MH = RuntimeHelper.downcallHandle(
        "gtk_binding_entry_add_signal",
        constants$1657.gtk_binding_entry_add_signal$FUNC, true
    );
    static final FunctionDescriptor gtk_binding_entry_add_signall$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_binding_entry_add_signall$MH = RuntimeHelper.downcallHandle(
        "gtk_binding_entry_add_signall",
        constants$1657.gtk_binding_entry_add_signall$FUNC, false
    );
    static final FunctionDescriptor gtk_binding_entry_add_signal_from_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_binding_entry_add_signal_from_string$MH = RuntimeHelper.downcallHandle(
        "gtk_binding_entry_add_signal_from_string",
        constants$1657.gtk_binding_entry_add_signal_from_string$FUNC, false
    );
    static final FunctionDescriptor gtk_binding_entry_remove$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_binding_entry_remove$MH = RuntimeHelper.downcallHandle(
        "gtk_binding_entry_remove",
        constants$1657.gtk_binding_entry_remove$FUNC, false
    );
    static final FunctionDescriptor gtk_builder_error_quark$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle gtk_builder_error_quark$MH = RuntimeHelper.downcallHandle(
        "gtk_builder_error_quark",
        constants$1657.gtk_builder_error_quark$FUNC, false
    );
}


