// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$946 {

    static final FunctionDescriptor glib_slistautoptr_cleanup_GSocketAddress$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GSocketAddress$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GSocketAddress",
        constants$946.glib_slistautoptr_cleanup_GSocketAddress$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GSocketAddress$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GSocketAddress$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GSocketAddress",
        constants$946.glib_queueautoptr_cleanup_GSocketAddress$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GSocketClient$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GSocketClient$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GSocketClient",
        constants$946.glib_autoptr_clear_GSocketClient$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GSocketClient$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GSocketClient$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GSocketClient",
        constants$946.glib_autoptr_cleanup_GSocketClient$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GSocketClient$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GSocketClient$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GSocketClient",
        constants$946.glib_listautoptr_cleanup_GSocketClient$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GSocketClient$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GSocketClient$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GSocketClient",
        constants$946.glib_slistautoptr_cleanup_GSocketClient$FUNC, false
    );
}


