// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$732 {

    static final FunctionDescriptor g_memory_monitor$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_memory_monitor$MH = RuntimeHelper.downcallHandle(
        "g_memory_monitor",
        constants$732.g_memory_monitor$FUNC, false
    );
    static final FunctionDescriptor g_IS_memory_monitor$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_IS_memory_monitor$MH = RuntimeHelper.downcallHandle(
        "g_IS_memory_monitor",
        constants$732.g_IS_memory_monitor$FUNC, false
    );
    static final FunctionDescriptor g_memory_monitor_GET_IFACE$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_memory_monitor_GET_IFACE$MH = RuntimeHelper.downcallHandle(
        "g_memory_monitor_GET_IFACE",
        constants$732.g_memory_monitor_GET_IFACE$FUNC, false
    );
    static final FunctionDescriptor g_memory_monitor_dup_default$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle g_memory_monitor_dup_default$MH = RuntimeHelper.downcallHandle(
        "g_memory_monitor_dup_default",
        constants$732.g_memory_monitor_dup_default$FUNC, false
    );
    static final FunctionDescriptor GReallocFunc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle GReallocFunc$MH = RuntimeHelper.downcallHandle(
        constants$732.GReallocFunc$FUNC, false
    );
}


