// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1924 {

    static final FunctionDescriptor gtk_radio_menu_item_new_with_label_from_widget$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_radio_menu_item_new_with_label_from_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_radio_menu_item_new_with_label_from_widget",
        constants$1924.gtk_radio_menu_item_new_with_label_from_widget$FUNC, false
    );
    static final FunctionDescriptor gtk_radio_menu_item_get_group$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_radio_menu_item_get_group$MH = RuntimeHelper.downcallHandle(
        "gtk_radio_menu_item_get_group",
        constants$1924.gtk_radio_menu_item_get_group$FUNC, false
    );
    static final FunctionDescriptor gtk_radio_menu_item_set_group$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_radio_menu_item_set_group$MH = RuntimeHelper.downcallHandle(
        "gtk_radio_menu_item_set_group",
        constants$1924.gtk_radio_menu_item_set_group$FUNC, false
    );
    static final FunctionDescriptor gtk_radio_menu_item_join_group$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_radio_menu_item_join_group$MH = RuntimeHelper.downcallHandle(
        "gtk_radio_menu_item_join_group",
        constants$1924.gtk_radio_menu_item_join_group$FUNC, false
    );
    static final FunctionDescriptor gtk_toggle_tool_button_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_toggle_tool_button_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_toggle_tool_button_get_type",
        constants$1924.gtk_toggle_tool_button_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_toggle_tool_button_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle gtk_toggle_tool_button_new$MH = RuntimeHelper.downcallHandle(
        "gtk_toggle_tool_button_new",
        constants$1924.gtk_toggle_tool_button_new$FUNC, false
    );
}


