// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$934 {

    static final FunctionDescriptor glib_autoptr_cleanup_GResolver$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GResolver$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GResolver",
        constants$934.glib_autoptr_cleanup_GResolver$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GResolver$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GResolver$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GResolver",
        constants$934.glib_listautoptr_cleanup_GResolver$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GResolver$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GResolver$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GResolver",
        constants$934.glib_slistautoptr_cleanup_GResolver$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GResolver$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GResolver$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GResolver",
        constants$934.glib_queueautoptr_cleanup_GResolver$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GResource$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GResource$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GResource",
        constants$934.glib_autoptr_clear_GResource$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GResource$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GResource$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GResource",
        constants$934.glib_autoptr_cleanup_GResource$FUNC, false
    );
}


