// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1038 {

    static final FunctionDescriptor pango_font_description_copy_static$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_font_description_copy_static$MH = RuntimeHelper.downcallHandle(
        "pango_font_description_copy_static",
        constants$1038.pango_font_description_copy_static$FUNC, false
    );
    static final FunctionDescriptor pango_font_description_hash$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_font_description_hash$MH = RuntimeHelper.downcallHandle(
        "pango_font_description_hash",
        constants$1038.pango_font_description_hash$FUNC, false
    );
    static final FunctionDescriptor pango_font_description_equal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_font_description_equal$MH = RuntimeHelper.downcallHandle(
        "pango_font_description_equal",
        constants$1038.pango_font_description_equal$FUNC, false
    );
    static final FunctionDescriptor pango_font_description_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_font_description_free$MH = RuntimeHelper.downcallHandle(
        "pango_font_description_free",
        constants$1038.pango_font_description_free$FUNC, false
    );
    static final FunctionDescriptor pango_font_descriptions_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pango_font_descriptions_free$MH = RuntimeHelper.downcallHandle(
        "pango_font_descriptions_free",
        constants$1038.pango_font_descriptions_free$FUNC, false
    );
    static final FunctionDescriptor pango_font_description_set_family$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_font_description_set_family$MH = RuntimeHelper.downcallHandle(
        "pango_font_description_set_family",
        constants$1038.pango_font_description_set_family$FUNC, false
    );
}


