// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2180 {

    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkEntryCompletion$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkEntryCompletion$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkEntryCompletion",
        constants$2180.glib_queueautoptr_cleanup_GtkEntryCompletion$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GtkEventBox$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GtkEventBox$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GtkEventBox",
        constants$2180.glib_autoptr_clear_GtkEventBox$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GtkEventBox$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GtkEventBox$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GtkEventBox",
        constants$2180.glib_autoptr_cleanup_GtkEventBox$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GtkEventBox$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GtkEventBox$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GtkEventBox",
        constants$2180.glib_listautoptr_cleanup_GtkEventBox$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GtkEventBox$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GtkEventBox$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GtkEventBox",
        constants$2180.glib_slistautoptr_cleanup_GtkEventBox$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GtkEventBox$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GtkEventBox$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GtkEventBox",
        constants$2180.glib_queueautoptr_cleanup_GtkEventBox$FUNC, false
    );
}


