// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2336 {

    static final MemorySegment GTK_STYLE_CLASS_TROUGH$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("trough");
    static final MemorySegment GTK_STYLE_CLASS_SCROLLBAR$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("scrollbar");
    static final MemorySegment GTK_STYLE_CLASS_SCROLLBARS_JUNCTION$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("scrollbars-junction");
    static final MemorySegment GTK_STYLE_CLASS_SCALE$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("scale");
    static final MemorySegment GTK_STYLE_CLASS_SCALE_HAS_MARKS_ABOVE$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("scale-has-marks-above");
    static final MemorySegment GTK_STYLE_CLASS_SCALE_HAS_MARKS_BELOW$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("scale-has-marks-below");
}


