// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1910 {

    static final FunctionDescriptor gtk_print_settings_set_page_set$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_print_settings_set_page_set$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_set_page_set",
        constants$1910.gtk_print_settings_set_page_set$FUNC, false
    );
    static final FunctionDescriptor gtk_print_settings_get_default_source$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_settings_get_default_source$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_get_default_source",
        constants$1910.gtk_print_settings_get_default_source$FUNC, false
    );
    static final FunctionDescriptor gtk_print_settings_set_default_source$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_settings_set_default_source$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_set_default_source",
        constants$1910.gtk_print_settings_set_default_source$FUNC, false
    );
    static final FunctionDescriptor gtk_print_settings_get_media_type$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_settings_get_media_type$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_get_media_type",
        constants$1910.gtk_print_settings_get_media_type$FUNC, false
    );
    static final FunctionDescriptor gtk_print_settings_set_media_type$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_settings_set_media_type$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_set_media_type",
        constants$1910.gtk_print_settings_set_media_type$FUNC, false
    );
    static final FunctionDescriptor gtk_print_settings_get_dither$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_print_settings_get_dither$MH = RuntimeHelper.downcallHandle(
        "gtk_print_settings_get_dither",
        constants$1910.gtk_print_settings_get_dither$FUNC, false
    );
}


