// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1785 {

    static final FunctionDescriptor gtk_icon_source_set_direction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_icon_source_set_direction$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_source_set_direction",
        constants$1785.gtk_icon_source_set_direction$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_source_set_state$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_icon_source_set_state$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_source_set_state",
        constants$1785.gtk_icon_source_set_state$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_source_set_size$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_icon_source_set_size$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_source_set_size",
        constants$1785.gtk_icon_source_set_size$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_source_get_direction$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_source_get_direction$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_source_get_direction",
        constants$1785.gtk_icon_source_get_direction$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_source_get_state$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_source_get_state$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_source_get_state",
        constants$1785.gtk_icon_source_get_state$FUNC, false
    );
    static final FunctionDescriptor gtk_icon_source_get_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_icon_source_get_size$MH = RuntimeHelper.downcallHandle(
        "gtk_icon_source_get_size",
        constants$1785.gtk_icon_source_get_size$FUNC, false
    );
}


