// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1007 {

    static final FunctionDescriptor hb_font_get_empty$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle hb_font_get_empty$MH = RuntimeHelper.downcallHandle(
        "hb_font_get_empty",
        constants$1007.hb_font_get_empty$FUNC, false
    );
    static final FunctionDescriptor hb_font_reference$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_font_reference$MH = RuntimeHelper.downcallHandle(
        "hb_font_reference",
        constants$1007.hb_font_reference$FUNC, false
    );
    static final FunctionDescriptor hb_font_destroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_font_destroy$MH = RuntimeHelper.downcallHandle(
        "hb_font_destroy",
        constants$1007.hb_font_destroy$FUNC, false
    );
    static final FunctionDescriptor hb_font_set_user_data$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle hb_font_set_user_data$MH = RuntimeHelper.downcallHandle(
        "hb_font_set_user_data",
        constants$1007.hb_font_set_user_data$FUNC, false
    );
    static final FunctionDescriptor hb_font_get_user_data$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_font_get_user_data$MH = RuntimeHelper.downcallHandle(
        "hb_font_get_user_data",
        constants$1007.hb_font_get_user_data$FUNC, false
    );
    static final FunctionDescriptor hb_font_make_immutable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_font_make_immutable$MH = RuntimeHelper.downcallHandle(
        "hb_font_make_immutable",
        constants$1007.hb_font_make_immutable$FUNC, false
    );
}


