// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1341 {

    static final FunctionDescriptor atk_object_get_description$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle atk_object_get_description$MH = RuntimeHelper.downcallHandle(
        "atk_object_get_description",
        constants$1341.atk_object_get_description$FUNC, false
    );
    static final FunctionDescriptor atk_object_get_parent$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle atk_object_get_parent$MH = RuntimeHelper.downcallHandle(
        "atk_object_get_parent",
        constants$1341.atk_object_get_parent$FUNC, false
    );
    static final FunctionDescriptor atk_object_peek_parent$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle atk_object_peek_parent$MH = RuntimeHelper.downcallHandle(
        "atk_object_peek_parent",
        constants$1341.atk_object_peek_parent$FUNC, false
    );
    static final FunctionDescriptor atk_object_get_n_accessible_children$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle atk_object_get_n_accessible_children$MH = RuntimeHelper.downcallHandle(
        "atk_object_get_n_accessible_children",
        constants$1341.atk_object_get_n_accessible_children$FUNC, false
    );
    static final FunctionDescriptor atk_object_ref_accessible_child$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle atk_object_ref_accessible_child$MH = RuntimeHelper.downcallHandle(
        "atk_object_ref_accessible_child",
        constants$1341.atk_object_ref_accessible_child$FUNC, false
    );
    static final FunctionDescriptor atk_object_ref_relation_set$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle atk_object_ref_relation_set$MH = RuntimeHelper.downcallHandle(
        "atk_object_ref_relation_set",
        constants$1341.atk_object_ref_relation_set$FUNC, false
    );
}


