// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2058 {

    static final FunctionDescriptor gtk_tree_view_column_sizing_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_tree_view_column_sizing_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_tree_view_column_sizing_get_type",
        constants$2058.gtk_tree_view_column_sizing_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_widget_help_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_widget_help_type_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_widget_help_type_get_type",
        constants$2058.gtk_widget_help_type_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_window_type_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_window_type_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_window_type_get_type",
        constants$2058.gtk_window_type_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_window_position_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_window_position_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_window_position_get_type",
        constants$2058.gtk_window_position_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_viewport_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_viewport_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_viewport_get_type",
        constants$2058.gtk_viewport_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_viewport_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_viewport_new$MH = RuntimeHelper.downcallHandle(
        "gtk_viewport_new",
        constants$2058.gtk_viewport_new$FUNC, false
    );
}


