// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1837 {

    static final FunctionDescriptor GtkListBoxForeachFunc$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GtkListBoxForeachFunc$MH = RuntimeHelper.downcallHandle(
        constants$1837.GtkListBoxForeachFunc$FUNC, false
    );
    static final FunctionDescriptor gtk_list_box_selected_foreach$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_box_selected_foreach$MH = RuntimeHelper.downcallHandle(
        "gtk_list_box_selected_foreach",
        constants$1837.gtk_list_box_selected_foreach$FUNC, false
    );
    static final FunctionDescriptor gtk_list_box_get_selected_rows$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_box_get_selected_rows$MH = RuntimeHelper.downcallHandle(
        "gtk_list_box_get_selected_rows",
        constants$1837.gtk_list_box_get_selected_rows$FUNC, false
    );
    static final FunctionDescriptor gtk_list_box_unselect_row$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_box_unselect_row$MH = RuntimeHelper.downcallHandle(
        "gtk_list_box_unselect_row",
        constants$1837.gtk_list_box_unselect_row$FUNC, false
    );
    static final FunctionDescriptor gtk_list_box_select_all$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_list_box_select_all$MH = RuntimeHelper.downcallHandle(
        "gtk_list_box_select_all",
        constants$1837.gtk_list_box_select_all$FUNC, false
    );
}


