// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1579 {

    static final FunctionDescriptor gtk_target_entry_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_target_entry_free$MH = RuntimeHelper.downcallHandle(
        "gtk_target_entry_free",
        constants$1579.gtk_target_entry_free$FUNC, false
    );
    static final FunctionDescriptor gtk_drag_get_data$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_drag_get_data$MH = RuntimeHelper.downcallHandle(
        "gtk_drag_get_data",
        constants$1579.gtk_drag_get_data$FUNC, false
    );
    static final FunctionDescriptor gtk_drag_finish$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_drag_finish$MH = RuntimeHelper.downcallHandle(
        "gtk_drag_finish",
        constants$1579.gtk_drag_finish$FUNC, false
    );
    static final FunctionDescriptor gtk_drag_get_source_widget$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_drag_get_source_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_drag_get_source_widget",
        constants$1579.gtk_drag_get_source_widget$FUNC, false
    );
    static final FunctionDescriptor gtk_drag_highlight$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_drag_highlight$MH = RuntimeHelper.downcallHandle(
        "gtk_drag_highlight",
        constants$1579.gtk_drag_highlight$FUNC, false
    );
    static final FunctionDescriptor gtk_drag_unhighlight$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_drag_unhighlight$MH = RuntimeHelper.downcallHandle(
        "gtk_drag_unhighlight",
        constants$1579.gtk_drag_unhighlight$FUNC, false
    );
}


