// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1527 {

    static final FunctionDescriptor gtk_cell_editable_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_cell_editable_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_editable_get_type",
        constants$1527.gtk_cell_editable_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_cell_editable_start_editing$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_cell_editable_start_editing$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_editable_start_editing",
        constants$1527.gtk_cell_editable_start_editing$FUNC, false
    );
    static final FunctionDescriptor gtk_cell_editable_editing_done$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_cell_editable_editing_done$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_editable_editing_done",
        constants$1527.gtk_cell_editable_editing_done$FUNC, false
    );
    static final FunctionDescriptor gtk_cell_editable_remove_widget$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_cell_editable_remove_widget$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_editable_remove_widget",
        constants$1527.gtk_cell_editable_remove_widget$FUNC, false
    );
    static final FunctionDescriptor gtk_cell_renderer_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gtk_cell_renderer_get_type$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_renderer_get_type",
        constants$1527.gtk_cell_renderer_get_type$FUNC, false
    );
    static final FunctionDescriptor gtk_cell_renderer_get_request_mode$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_cell_renderer_get_request_mode$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_renderer_get_request_mode",
        constants$1527.gtk_cell_renderer_get_request_mode$FUNC, false
    );
}


