// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1068 {

    static final FunctionDescriptor pango_context_get_metrics$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_context_get_metrics$MH = RuntimeHelper.downcallHandle(
        "pango_context_get_metrics",
        constants$1068.pango_context_get_metrics$FUNC, false
    );
    static final FunctionDescriptor pango_context_set_font_description$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_context_set_font_description$MH = RuntimeHelper.downcallHandle(
        "pango_context_set_font_description",
        constants$1068.pango_context_set_font_description$FUNC, false
    );
    static final FunctionDescriptor pango_context_get_font_description$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_context_get_font_description$MH = RuntimeHelper.downcallHandle(
        "pango_context_get_font_description",
        constants$1068.pango_context_get_font_description$FUNC, false
    );
    static final FunctionDescriptor pango_context_get_language$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_context_get_language$MH = RuntimeHelper.downcallHandle(
        "pango_context_get_language",
        constants$1068.pango_context_get_language$FUNC, false
    );
    static final FunctionDescriptor pango_context_set_language$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle pango_context_set_language$MH = RuntimeHelper.downcallHandle(
        "pango_context_set_language",
        constants$1068.pango_context_set_language$FUNC, false
    );
    static final FunctionDescriptor pango_context_set_base_dir$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle pango_context_set_base_dir$MH = RuntimeHelper.downcallHandle(
        "pango_context_set_base_dir",
        constants$1068.pango_context_set_base_dir$FUNC, false
    );
}


