// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1019 {

    static final FunctionDescriptor hb_buffer_has_positions$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_buffer_has_positions$MH = RuntimeHelper.downcallHandle(
        "hb_buffer_has_positions",
        constants$1019.hb_buffer_has_positions$FUNC, false
    );
    static final FunctionDescriptor hb_buffer_normalize_glyphs$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle hb_buffer_normalize_glyphs$MH = RuntimeHelper.downcallHandle(
        "hb_buffer_normalize_glyphs",
        constants$1019.hb_buffer_normalize_glyphs$FUNC, false
    );
    static final FunctionDescriptor hb_buffer_serialize_format_from_string$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle hb_buffer_serialize_format_from_string$MH = RuntimeHelper.downcallHandle(
        "hb_buffer_serialize_format_from_string",
        constants$1019.hb_buffer_serialize_format_from_string$FUNC, false
    );
    static final FunctionDescriptor hb_buffer_serialize_format_to_string$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle hb_buffer_serialize_format_to_string$MH = RuntimeHelper.downcallHandle(
        "hb_buffer_serialize_format_to_string",
        constants$1019.hb_buffer_serialize_format_to_string$FUNC, false
    );
    static final FunctionDescriptor hb_buffer_serialize_list_formats$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle hb_buffer_serialize_list_formats$MH = RuntimeHelper.downcallHandle(
        "hb_buffer_serialize_list_formats",
        constants$1019.hb_buffer_serialize_list_formats$FUNC, false
    );
    static final FunctionDescriptor hb_buffer_serialize_glyphs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle hb_buffer_serialize_glyphs$MH = RuntimeHelper.downcallHandle(
        "hb_buffer_serialize_glyphs",
        constants$1019.hb_buffer_serialize_glyphs$FUNC, false
    );
}


