// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$290 {

    static final FunctionDescriptor __stpncpy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle __stpncpy$MH = RuntimeHelper.downcallHandle(
        "__stpncpy",
        constants$290.__stpncpy$FUNC, false
    );
    static final FunctionDescriptor stpncpy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle stpncpy$MH = RuntimeHelper.downcallHandle(
        "stpncpy",
        constants$290.stpncpy$FUNC, false
    );
    static final FunctionDescriptor g_slice_alloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_slice_alloc$MH = RuntimeHelper.downcallHandle(
        "g_slice_alloc",
        constants$290.g_slice_alloc$FUNC, false
    );
    static final FunctionDescriptor g_slice_alloc0$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle g_slice_alloc0$MH = RuntimeHelper.downcallHandle(
        "g_slice_alloc0",
        constants$290.g_slice_alloc0$FUNC, false
    );
    static final FunctionDescriptor g_slice_copy$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_slice_copy$MH = RuntimeHelper.downcallHandle(
        "g_slice_copy",
        constants$290.g_slice_copy$FUNC, false
    );
    static final FunctionDescriptor g_slice_free1$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_slice_free1$MH = RuntimeHelper.downcallHandle(
        "g_slice_free1",
        constants$290.g_slice_free1$FUNC, false
    );
}


