// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1284 {

    static final FunctionDescriptor gdk_cairo_draw_from_gl$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_cairo_draw_from_gl$MH = RuntimeHelper.downcallHandle(
        "gdk_cairo_draw_from_gl",
        constants$1284.gdk_cairo_draw_from_gl$FUNC, false
    );
    static final FunctionDescriptor gdk_cairo_get_drawing_context$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gdk_cairo_get_drawing_context$MH = RuntimeHelper.downcallHandle(
        "gdk_cairo_get_drawing_context",
        constants$1284.gdk_cairo_get_drawing_context$FUNC, false
    );
    static final FunctionDescriptor gdk_cursor_get_type$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle gdk_cursor_get_type$MH = RuntimeHelper.downcallHandle(
        "gdk_cursor_get_type",
        constants$1284.gdk_cursor_get_type$FUNC, false
    );
    static final FunctionDescriptor gdk_cursor_new_for_display$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_cursor_new_for_display$MH = RuntimeHelper.downcallHandle(
        "gdk_cursor_new_for_display",
        constants$1284.gdk_cursor_new_for_display$FUNC, false
    );
    static final FunctionDescriptor gdk_cursor_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_cursor_new$MH = RuntimeHelper.downcallHandle(
        "gdk_cursor_new",
        constants$1284.gdk_cursor_new$FUNC, false
    );
    static final FunctionDescriptor gdk_cursor_new_from_pixbuf$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gdk_cursor_new_from_pixbuf$MH = RuntimeHelper.downcallHandle(
        "gdk_cursor_new_from_pixbuf",
        constants$1284.gdk_cursor_new_from_pixbuf$FUNC, false
    );
}


