// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2106 {

    static final FunctionDescriptor gtk_toggle_action_toggled$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_toggle_action_toggled$MH = RuntimeHelper.downcallHandle(
        "gtk_toggle_action_toggled",
        constants$2106.gtk_toggle_action_toggled$FUNC, false
    );
    static final FunctionDescriptor gtk_toggle_action_set_active$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_toggle_action_set_active$MH = RuntimeHelper.downcallHandle(
        "gtk_toggle_action_set_active",
        constants$2106.gtk_toggle_action_set_active$FUNC, false
    );
    static final FunctionDescriptor gtk_toggle_action_get_active$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_toggle_action_get_active$MH = RuntimeHelper.downcallHandle(
        "gtk_toggle_action_get_active",
        constants$2106.gtk_toggle_action_get_active$FUNC, false
    );
    static final FunctionDescriptor gtk_toggle_action_set_draw_as_radio$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_toggle_action_set_draw_as_radio$MH = RuntimeHelper.downcallHandle(
        "gtk_toggle_action_set_draw_as_radio",
        constants$2106.gtk_toggle_action_set_draw_as_radio$FUNC, false
    );
    static final FunctionDescriptor gtk_toggle_action_get_draw_as_radio$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_toggle_action_get_draw_as_radio$MH = RuntimeHelper.downcallHandle(
        "gtk_toggle_action_get_draw_as_radio",
        constants$2106.gtk_toggle_action_get_draw_as_radio$FUNC, false
    );
    static final FunctionDescriptor _gtk_toggle_action_set_active$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle _gtk_toggle_action_set_active$MH = RuntimeHelper.downcallHandle(
        "_gtk_toggle_action_set_active",
        constants$2106._gtk_toggle_action_set_active$FUNC, false
    );
}


