// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1529 {

    static final FunctionDescriptor gtk_cell_renderer_get_size$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_cell_renderer_get_size$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_renderer_get_size",
        constants$1529.gtk_cell_renderer_get_size$FUNC, false
    );
    static final FunctionDescriptor gtk_cell_renderer_render$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_cell_renderer_render$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_renderer_render",
        constants$1529.gtk_cell_renderer_render$FUNC, false
    );
    static final FunctionDescriptor gtk_cell_renderer_activate$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_cell_renderer_activate$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_renderer_activate",
        constants$1529.gtk_cell_renderer_activate$FUNC, false
    );
    static final FunctionDescriptor gtk_cell_renderer_start_editing$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_cell_renderer_start_editing$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_renderer_start_editing",
        constants$1529.gtk_cell_renderer_start_editing$FUNC, false
    );
    static final FunctionDescriptor gtk_cell_renderer_set_fixed_size$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_cell_renderer_set_fixed_size$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_renderer_set_fixed_size",
        constants$1529.gtk_cell_renderer_set_fixed_size$FUNC, false
    );
    static final FunctionDescriptor gtk_cell_renderer_get_fixed_size$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_cell_renderer_get_fixed_size$MH = RuntimeHelper.downcallHandle(
        "gtk_cell_renderer_get_fixed_size",
        constants$1529.gtk_cell_renderer_get_fixed_size$FUNC, false
    );
}


