// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2084 {

    static final FunctionDescriptor gtk_alignment_new$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle gtk_alignment_new$MH = RuntimeHelper.downcallHandle(
        "gtk_alignment_new",
        constants$2084.gtk_alignment_new$FUNC, false
    );
    static final FunctionDescriptor gtk_alignment_set$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    static final MethodHandle gtk_alignment_set$MH = RuntimeHelper.downcallHandle(
        "gtk_alignment_set",
        constants$2084.gtk_alignment_set$FUNC, false
    );
    static final FunctionDescriptor gtk_alignment_set_padding$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_alignment_set_padding$MH = RuntimeHelper.downcallHandle(
        "gtk_alignment_set_padding",
        constants$2084.gtk_alignment_set_padding$FUNC, false
    );
    static final FunctionDescriptor gtk_alignment_get_padding$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_alignment_get_padding$MH = RuntimeHelper.downcallHandle(
        "gtk_alignment_get_padding",
        constants$2084.gtk_alignment_get_padding$FUNC, false
    );
    static final FunctionDescriptor GtkColorSelectionChangePaletteFunc$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle GtkColorSelectionChangePaletteFunc$MH = RuntimeHelper.downcallHandle(
        constants$2084.GtkColorSelectionChangePaletteFunc$FUNC, false
    );
}


