// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1608 {

    static final FunctionDescriptor gtk_entry_get_activates_default$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_get_activates_default$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_get_activates_default",
        constants$1608.gtk_entry_get_activates_default$FUNC, false
    );
    static final FunctionDescriptor gtk_entry_set_width_chars$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_set_width_chars$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_set_width_chars",
        constants$1608.gtk_entry_set_width_chars$FUNC, false
    );
    static final FunctionDescriptor gtk_entry_get_width_chars$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_get_width_chars$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_get_width_chars",
        constants$1608.gtk_entry_get_width_chars$FUNC, false
    );
    static final FunctionDescriptor gtk_entry_set_max_width_chars$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_entry_set_max_width_chars$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_set_max_width_chars",
        constants$1608.gtk_entry_set_max_width_chars$FUNC, false
    );
    static final FunctionDescriptor gtk_entry_get_max_width_chars$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_get_max_width_chars$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_get_max_width_chars",
        constants$1608.gtk_entry_get_max_width_chars$FUNC, false
    );
    static final FunctionDescriptor gtk_entry_set_text$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_entry_set_text$MH = RuntimeHelper.downcallHandle(
        "gtk_entry_set_text",
        constants$1608.gtk_entry_set_text$FUNC, false
    );
}


