// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$833 {

    static final FunctionDescriptor GTaskThreadFunc$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle GTaskThreadFunc$MH = RuntimeHelper.downcallHandle(
        constants$833.GTaskThreadFunc$FUNC, false
    );
    static final FunctionDescriptor g_task_run_in_thread$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_task_run_in_thread$MH = RuntimeHelper.downcallHandle(
        "g_task_run_in_thread",
        constants$833.g_task_run_in_thread$FUNC, false
    );
    static final FunctionDescriptor g_task_run_in_thread_sync$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_task_run_in_thread_sync$MH = RuntimeHelper.downcallHandle(
        "g_task_run_in_thread_sync",
        constants$833.g_task_run_in_thread_sync$FUNC, false
    );
    static final FunctionDescriptor g_task_set_return_on_cancel$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle g_task_set_return_on_cancel$MH = RuntimeHelper.downcallHandle(
        "g_task_set_return_on_cancel",
        constants$833.g_task_set_return_on_cancel$FUNC, false
    );
    static final FunctionDescriptor g_task_get_return_on_cancel$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_task_get_return_on_cancel$MH = RuntimeHelper.downcallHandle(
        "g_task_get_return_on_cancel",
        constants$833.g_task_get_return_on_cancel$FUNC, false
    );
    static final FunctionDescriptor g_task_attach_source$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle g_task_attach_source$MH = RuntimeHelper.downcallHandle(
        "g_task_attach_source",
        constants$833.g_task_attach_source$FUNC, false
    );
}


