// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1763 {

    static final FunctionDescriptor gtk_gesture_single_get_touch_only$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_gesture_single_get_touch_only$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_single_get_touch_only",
        constants$1763.gtk_gesture_single_get_touch_only$FUNC, false
    );
    static final FunctionDescriptor gtk_gesture_single_set_touch_only$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_gesture_single_set_touch_only$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_single_set_touch_only",
        constants$1763.gtk_gesture_single_set_touch_only$FUNC, false
    );
    static final FunctionDescriptor gtk_gesture_single_get_exclusive$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_gesture_single_get_exclusive$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_single_get_exclusive",
        constants$1763.gtk_gesture_single_get_exclusive$FUNC, false
    );
    static final FunctionDescriptor gtk_gesture_single_set_exclusive$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_gesture_single_set_exclusive$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_single_set_exclusive",
        constants$1763.gtk_gesture_single_set_exclusive$FUNC, false
    );
    static final FunctionDescriptor gtk_gesture_single_get_button$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_gesture_single_get_button$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_single_get_button",
        constants$1763.gtk_gesture_single_get_button$FUNC, false
    );
    static final FunctionDescriptor gtk_gesture_single_set_button$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_gesture_single_set_button$MH = RuntimeHelper.downcallHandle(
        "gtk_gesture_single_set_button",
        constants$1763.gtk_gesture_single_set_button$FUNC, false
    );
}


