// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$909 {

    static final FunctionDescriptor glib_autoptr_cleanup_GInetSocketAddress$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GInetSocketAddress$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GInetSocketAddress",
        constants$909.glib_autoptr_cleanup_GInetSocketAddress$FUNC, false
    );
    static final FunctionDescriptor glib_listautoptr_cleanup_GInetSocketAddress$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_listautoptr_cleanup_GInetSocketAddress$MH = RuntimeHelper.downcallHandle(
        "glib_listautoptr_cleanup_GInetSocketAddress",
        constants$909.glib_listautoptr_cleanup_GInetSocketAddress$FUNC, false
    );
    static final FunctionDescriptor glib_slistautoptr_cleanup_GInetSocketAddress$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_slistautoptr_cleanup_GInetSocketAddress$MH = RuntimeHelper.downcallHandle(
        "glib_slistautoptr_cleanup_GInetSocketAddress",
        constants$909.glib_slistautoptr_cleanup_GInetSocketAddress$FUNC, false
    );
    static final FunctionDescriptor glib_queueautoptr_cleanup_GInetSocketAddress$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_queueautoptr_cleanup_GInetSocketAddress$MH = RuntimeHelper.downcallHandle(
        "glib_queueautoptr_cleanup_GInetSocketAddress",
        constants$909.glib_queueautoptr_cleanup_GInetSocketAddress$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_clear_GInitable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_clear_GInitable$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_clear_GInitable",
        constants$909.glib_autoptr_clear_GInitable$FUNC, false
    );
    static final FunctionDescriptor glib_autoptr_cleanup_GInitable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle glib_autoptr_cleanup_GInitable$MH = RuntimeHelper.downcallHandle(
        "glib_autoptr_cleanup_GInitable",
        constants$909.glib_autoptr_cleanup_GInitable$FUNC, false
    );
}


