// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1129 {

    static final FunctionDescriptor cairo_copy_page$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_copy_page$MH = RuntimeHelper.downcallHandle(
        "cairo_copy_page",
        constants$1129.cairo_copy_page$FUNC, false
    );
    static final FunctionDescriptor cairo_show_page$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_show_page$MH = RuntimeHelper.downcallHandle(
        "cairo_show_page",
        constants$1129.cairo_show_page$FUNC, false
    );
    static final FunctionDescriptor cairo_in_stroke$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle cairo_in_stroke$MH = RuntimeHelper.downcallHandle(
        "cairo_in_stroke",
        constants$1129.cairo_in_stroke$FUNC, false
    );
    static final FunctionDescriptor cairo_in_fill$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle cairo_in_fill$MH = RuntimeHelper.downcallHandle(
        "cairo_in_fill",
        constants$1129.cairo_in_fill$FUNC, false
    );
    static final FunctionDescriptor cairo_in_clip$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT,
        Constants$root.C_DOUBLE$LAYOUT
    );
    static final MethodHandle cairo_in_clip$MH = RuntimeHelper.downcallHandle(
        "cairo_in_clip",
        constants$1129.cairo_in_clip$FUNC, false
    );
    static final FunctionDescriptor cairo_stroke_extents$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle cairo_stroke_extents$MH = RuntimeHelper.downcallHandle(
        "cairo_stroke_extents",
        constants$1129.cairo_stroke_extents$FUNC, false
    );
}


