// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1439 {

    static final FunctionDescriptor gtk_container_get_focus_child$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_container_get_focus_child$MH = RuntimeHelper.downcallHandle(
        "gtk_container_get_focus_child",
        constants$1439.gtk_container_get_focus_child$FUNC, false
    );
    static final FunctionDescriptor gtk_container_set_focus_vadjustment$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_container_set_focus_vadjustment$MH = RuntimeHelper.downcallHandle(
        "gtk_container_set_focus_vadjustment",
        constants$1439.gtk_container_set_focus_vadjustment$FUNC, false
    );
    static final FunctionDescriptor gtk_container_get_focus_vadjustment$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_container_get_focus_vadjustment$MH = RuntimeHelper.downcallHandle(
        "gtk_container_get_focus_vadjustment",
        constants$1439.gtk_container_get_focus_vadjustment$FUNC, false
    );
    static final FunctionDescriptor gtk_container_set_focus_hadjustment$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_container_set_focus_hadjustment$MH = RuntimeHelper.downcallHandle(
        "gtk_container_set_focus_hadjustment",
        constants$1439.gtk_container_set_focus_hadjustment$FUNC, false
    );
    static final FunctionDescriptor gtk_container_get_focus_hadjustment$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_container_get_focus_hadjustment$MH = RuntimeHelper.downcallHandle(
        "gtk_container_get_focus_hadjustment",
        constants$1439.gtk_container_get_focus_hadjustment$FUNC, false
    );
    static final FunctionDescriptor gtk_container_resize_children$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_container_resize_children$MH = RuntimeHelper.downcallHandle(
        "gtk_container_resize_children",
        constants$1439.gtk_container_resize_children$FUNC, false
    );
}


