// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$1846 {

    static final FunctionDescriptor gtk_main_level$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle gtk_main_level$MH = RuntimeHelper.downcallHandle(
        "gtk_main_level",
        constants$1846.gtk_main_level$FUNC, false
    );
    static final FunctionDescriptor gtk_main_quit$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle gtk_main_quit$MH = RuntimeHelper.downcallHandle(
        "gtk_main_quit",
        constants$1846.gtk_main_quit$FUNC, false
    );
    static final FunctionDescriptor gtk_main_iteration$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle gtk_main_iteration$MH = RuntimeHelper.downcallHandle(
        "gtk_main_iteration",
        constants$1846.gtk_main_iteration$FUNC, false
    );
    static final FunctionDescriptor gtk_main_iteration_do$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle gtk_main_iteration_do$MH = RuntimeHelper.downcallHandle(
        "gtk_main_iteration_do",
        constants$1846.gtk_main_iteration_do$FUNC, false
    );
    static final FunctionDescriptor gtk_true$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle gtk_true$MH = RuntimeHelper.downcallHandle(
        "gtk_true",
        constants$1846.gtk_true$FUNC, false
    );
    static final FunctionDescriptor gtk_false$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle gtk_false$MH = RuntimeHelper.downcallHandle(
        "gtk_false",
        constants$1846.gtk_false$FUNC, false
    );
}


