// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$2071 {

    static final FunctionDescriptor gtk_action_create_menu$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_action_create_menu$MH = RuntimeHelper.downcallHandle(
        "gtk_action_create_menu",
        constants$2071.gtk_action_create_menu$FUNC, false
    );
    static final FunctionDescriptor gtk_action_get_proxies$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_action_get_proxies$MH = RuntimeHelper.downcallHandle(
        "gtk_action_get_proxies",
        constants$2071.gtk_action_get_proxies$FUNC, false
    );
    static final FunctionDescriptor gtk_action_connect_accelerator$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_action_connect_accelerator$MH = RuntimeHelper.downcallHandle(
        "gtk_action_connect_accelerator",
        constants$2071.gtk_action_connect_accelerator$FUNC, false
    );
    static final FunctionDescriptor gtk_action_disconnect_accelerator$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_action_disconnect_accelerator$MH = RuntimeHelper.downcallHandle(
        "gtk_action_disconnect_accelerator",
        constants$2071.gtk_action_disconnect_accelerator$FUNC, false
    );
    static final FunctionDescriptor gtk_action_get_accel_path$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_action_get_accel_path$MH = RuntimeHelper.downcallHandle(
        "gtk_action_get_accel_path",
        constants$2071.gtk_action_get_accel_path$FUNC, false
    );
    static final FunctionDescriptor gtk_action_get_accel_closure$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle gtk_action_get_accel_closure$MH = RuntimeHelper.downcallHandle(
        "gtk_action_get_accel_closure",
        constants$2071.gtk_action_get_accel_closure$FUNC, false
    );
}


