// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GCompareDataFunc {

    int apply(jdk.incubator.foreign.MemoryAddress a, jdk.incubator.foreign.MemoryAddress b, jdk.incubator.foreign.MemoryAddress user_data);
    static NativeSymbol allocate(GCompareDataFunc fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GCompareDataFunc.class, fi, constants$6.GCompareDataFunc$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static GCompareDataFunc ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GCompareDataFunc::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress a, jdk.incubator.foreign.MemoryAddress b, jdk.incubator.foreign.MemoryAddress user_data) -> {
            try {
                return (int)constants$6.GCompareDataFunc$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)a, (jdk.incubator.foreign.Addressable)b, (jdk.incubator.foreign.Addressable)user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


