// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GObjectSetPropertyFunc {

    void apply(jdk.incubator.foreign.MemoryAddress object, int property_id, jdk.incubator.foreign.MemoryAddress value, jdk.incubator.foreign.MemoryAddress pspec);
    static NativeSymbol allocate(GObjectSetPropertyFunc fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GObjectSetPropertyFunc.class, fi, constants$466.GObjectSetPropertyFunc$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static GObjectSetPropertyFunc ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GObjectSetPropertyFunc::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress object, int property_id, jdk.incubator.foreign.MemoryAddress value, jdk.incubator.foreign.MemoryAddress pspec) -> {
            try {
                constants$466.GObjectSetPropertyFunc$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)object, property_id, (jdk.incubator.foreign.Addressable)value, (jdk.incubator.foreign.Addressable)pspec);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


