// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GOptionErrorFunc {

    void apply(jdk.incubator.foreign.MemoryAddress context, jdk.incubator.foreign.MemoryAddress group, jdk.incubator.foreign.MemoryAddress data, jdk.incubator.foreign.MemoryAddress error);
    static NativeSymbol allocate(GOptionErrorFunc fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GOptionErrorFunc.class, fi, constants$242.GOptionErrorFunc$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static GOptionErrorFunc ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GOptionErrorFunc::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress context, jdk.incubator.foreign.MemoryAddress group, jdk.incubator.foreign.MemoryAddress data, jdk.incubator.foreign.MemoryAddress error) -> {
            try {
                constants$242.GOptionErrorFunc$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)context, (jdk.incubator.foreign.Addressable)group, (jdk.incubator.foreign.Addressable)data, (jdk.incubator.foreign.Addressable)error);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


