// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GtkClipboardURIReceivedFunc {

    void apply(jdk.incubator.foreign.MemoryAddress clipboard, jdk.incubator.foreign.MemoryAddress uris, jdk.incubator.foreign.MemoryAddress data);
    static NativeSymbol allocate(GtkClipboardURIReceivedFunc fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GtkClipboardURIReceivedFunc.class, fi, constants$1694.GtkClipboardURIReceivedFunc$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static GtkClipboardURIReceivedFunc ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GtkClipboardURIReceivedFunc::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress clipboard, jdk.incubator.foreign.MemoryAddress uris, jdk.incubator.foreign.MemoryAddress data) -> {
            try {
                constants$1694.GtkClipboardURIReceivedFunc$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)clipboard, (jdk.incubator.foreign.Addressable)uris, (jdk.incubator.foreign.Addressable)data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


