// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GtkFlowBoxFilterFunc {

    int apply(jdk.incubator.foreign.MemoryAddress child, jdk.incubator.foreign.MemoryAddress user_data);
    static NativeSymbol allocate(GtkFlowBoxFilterFunc fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GtkFlowBoxFilterFunc.class, fi, constants$1751.GtkFlowBoxFilterFunc$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static GtkFlowBoxFilterFunc ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GtkFlowBoxFilterFunc::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress child, jdk.incubator.foreign.MemoryAddress user_data) -> {
            try {
                return (int)constants$1751.GtkFlowBoxFilterFunc$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)child, (jdk.incubator.foreign.Addressable)user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


