// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GtkIconViewForeachFunc {

    void apply(jdk.incubator.foreign.MemoryAddress icon_view, jdk.incubator.foreign.MemoryAddress path, jdk.incubator.foreign.MemoryAddress data);
    static NativeSymbol allocate(GtkIconViewForeachFunc fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GtkIconViewForeachFunc.class, fi, constants$1810.GtkIconViewForeachFunc$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static GtkIconViewForeachFunc ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GtkIconViewForeachFunc::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress icon_view, jdk.incubator.foreign.MemoryAddress path, jdk.incubator.foreign.MemoryAddress data) -> {
            try {
                constants$1810.GtkIconViewForeachFunc$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)icon_view, (jdk.incubator.foreign.Addressable)path, (jdk.incubator.foreign.Addressable)data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


