// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GtkListBoxForeachFunc {

    void apply(jdk.incubator.foreign.MemoryAddress box, jdk.incubator.foreign.MemoryAddress row, jdk.incubator.foreign.MemoryAddress user_data);
    static NativeSymbol allocate(GtkListBoxForeachFunc fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GtkListBoxForeachFunc.class, fi, constants$1837.GtkListBoxForeachFunc$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static GtkListBoxForeachFunc ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GtkListBoxForeachFunc::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress box, jdk.incubator.foreign.MemoryAddress row, jdk.incubator.foreign.MemoryAddress user_data) -> {
            try {
                constants$1837.GtkListBoxForeachFunc$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)box, (jdk.incubator.foreign.Addressable)row, (jdk.incubator.foreign.Addressable)user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


