// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GtkStylePropertyParser {

    int apply(jdk.incubator.foreign.MemoryAddress string, jdk.incubator.foreign.MemoryAddress value, jdk.incubator.foreign.MemoryAddress error);
    static NativeSymbol allocate(GtkStylePropertyParser fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GtkStylePropertyParser.class, fi, constants$1786.GtkStylePropertyParser$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static GtkStylePropertyParser ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GtkStylePropertyParser::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress string, jdk.incubator.foreign.MemoryAddress value, jdk.incubator.foreign.MemoryAddress error) -> {
            try {
                return (int)constants$1786.GtkStylePropertyParser$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)string, (jdk.incubator.foreign.Addressable)value, (jdk.incubator.foreign.Addressable)error);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


