// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GtkTreeDestroyCountFunc {

    void apply(jdk.incubator.foreign.MemoryAddress tree_view, jdk.incubator.foreign.MemoryAddress path, int children, jdk.incubator.foreign.MemoryAddress user_data);
    static NativeSymbol allocate(GtkTreeDestroyCountFunc fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GtkTreeDestroyCountFunc.class, fi, constants$1631.GtkTreeDestroyCountFunc$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static GtkTreeDestroyCountFunc ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GtkTreeDestroyCountFunc::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress tree_view, jdk.incubator.foreign.MemoryAddress path, int children, jdk.incubator.foreign.MemoryAddress user_data) -> {
            try {
                constants$1632.GtkTreeDestroyCountFunc$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)tree_view, (jdk.incubator.foreign.Addressable)path, children, (jdk.incubator.foreign.Addressable)user_data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


