// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GtkTreeModelForeachFunc {

    int apply(jdk.incubator.foreign.MemoryAddress model, jdk.incubator.foreign.MemoryAddress path, jdk.incubator.foreign.MemoryAddress iter, jdk.incubator.foreign.MemoryAddress data);
    static NativeSymbol allocate(GtkTreeModelForeachFunc fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GtkTreeModelForeachFunc.class, fi, constants$1516.GtkTreeModelForeachFunc$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I", scope);
    }
    static GtkTreeModelForeachFunc ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GtkTreeModelForeachFunc::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress model, jdk.incubator.foreign.MemoryAddress path, jdk.incubator.foreign.MemoryAddress iter, jdk.incubator.foreign.MemoryAddress data) -> {
            try {
                return (int)constants$1516.GtkTreeModelForeachFunc$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)model, (jdk.incubator.foreign.Addressable)path, (jdk.incubator.foreign.Addressable)iter, (jdk.incubator.foreign.Addressable)data);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


