// Generated by jextract

package gtk3;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public interface GTypeInterfaceCheckFunc {

    void apply(jdk.incubator.foreign.MemoryAddress check_data, jdk.incubator.foreign.MemoryAddress g_iface);
    static NativeSymbol allocate(GTypeInterfaceCheckFunc fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(GTypeInterfaceCheckFunc.class, fi, constants$422.GTypeInterfaceCheckFunc$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V", scope);
    }
    static GTypeInterfaceCheckFunc ofAddress(MemoryAddress addr, ResourceScope scope) {
        NativeSymbol symbol = NativeSymbol.ofAddress("GTypeInterfaceCheckFunc::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress check_data, jdk.incubator.foreign.MemoryAddress g_iface) -> {
            try {
                constants$423.GTypeInterfaceCheckFunc$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)check_data, (jdk.incubator.foreign.Addressable)g_iface);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


